### ISSUE TITLE
"TopologyException: Input geom 0 is invalid: Self-intersection" error when training dbnet on LSVT dataset

### ISSUE THREAD

**Issue by jiyzhang** [open-mmlab/mmocr#1004]
I followed the steps 
https://github.com/open-mmlab/mmocr/pull/896

but I encountered this error every time when trying to train dbnet with LSVT dataset: 
This issue can be repeated on mmocr 0.5.0 and the latest version 0.6.0. 

2022-05-07 18:06:07,355 - mmocr - INFO - Epoch [1][285/1500]    lr: 1.901e-05, eta: 6:12:53, time: 0.755, data_time: 0.094, memory: 14952, loss_prob: 3.5966, loss_db: 0.6905, loss_thr: 1.1102, loss: 5.3974
2022-05-07 18:06:11,182 - mmocr - INFO - Epoch [1][290/1500]    lr: 1.935e-05, eta: 6:12:56, time: 0.765, data_time: 0.100, memory: 14952, loss_prob: 3.5557, loss_db: 0.6624, loss_thr: 1.0861, loss: 5.3042
2022-05-07 18:06:14,534 - mmocr - INFO - Epoch [1][295/1500]    lr: 1.968e-05, eta: 6:12:10, time: 0.670, data_time: 0.007, memory: 14952, loss_prob: 3.5366, loss_db: 0.6394, loss_thr: 1.0698, loss: 5.2458
2022-05-07 18:06:18,330 - mmocr - INFO - Epoch [1][300/1500]    lr: 2.001e-05, eta: 6:12:10, time: 0.759, data_time: 0.099, memory: 14952, loss_prob: 3.5197, loss_db: 0.6452, loss_thr: 1.0930, loss: 5.2580
TopologyException: Input geom 0 is invalid: Self-intersection at 751.74675395698659 1391.9170255665726
2022-05-07 18:06:22,135 - mmocr - INFO - Epoch [1][305/1500]    lr: 2.035e-05, eta: 6:12:11, time: 0.761, data_time: 0.096, memory: 14952, loss_prob: 3.4960, loss_db: 0.6374, loss_thr: 1.0854, loss: 5.2187
2022-05-07 18:06:25,477 - mmocr - INFO - Epoch [1][310/1500]    lr: 2.068e-05, eta: 6:11:27, time: 0.668, data_time: 0.007, memory: 14952, loss_prob: 3.4913, loss_db: 0.5921, loss_thr: 1.0352, loss: 5.1186
2022-05-07 18:06:29,262 - mmocr - INFO - Epoch [1][315/1500]    lr: 2.101e-05, eta: 6:11:26, time: 0.757, data_time: 0.094, memory: 14952, loss_prob: 3.4591, loss_db: 0.5864, loss_thr: 1.0409, loss: 5.0865
Traceback (most recent call last):
  File "tools/train.py", line 230, in <module>
    main()
  File "tools/train.py", line 219, in main
    train_detector(
  File "/home/richardz/openmmlab/mmocr060/mmocr/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
shapely.errors.TopologicalError: Caught TopologicalError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 218, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 241, in prepare_train_img
    return self.pipeline(results)
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/richardz/openmmlab/mmocr060/mmocr/datasets/pipelines/dbnet_transforms.py", line 83, in __call__
    self.may_augment_annotation(aug, shape, target_shape, results)
  File "/home/richardz/openmmlab/mmocr060/mmocr/datasets/pipelines/dbnet_transforms.py", line 94, in may_augment_annotation
    masks = self.may_augment_poly(aug, shape, results[key])
  File "/home/richardz/openmmlab/mmocr060/mmocr/datasets/pipelines/dbnet_transforms.py", line 133, in may_augment_poly
    imgaug_polys = aug.augment_polygons(
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/imgaug/augmentables/polys.py", line 1806, in clip_out_of_image
    return self.copy().clip_out_of_image_()
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/imgaug/augmentables/polys.py", line 1777, in clip_out_of_image_
    self.polygons = [
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/imgaug/augmentables/polys.py", line 1780, in <listcomp>
    for poly_clipped in poly.clip_out_of_image(self.shape)]
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/imgaug/augmentables/polys.py", line 591, in clip_out_of_image
    multipoly_inter_shapely = poly_shapely.intersection(poly_image)
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/shapely/geometry/base.py", line 689, in intersection
    return geom_factory(self.impl['intersection'](self, other))
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/shapely/topology.py", line 72, in __call__
    self._check_topology(err, this, other)
  File "/home/richardz/anaconda3/envs/openmmlab/lib/python3.8/site-packages/shapely/topology.py", line 37, in _check_topology
    raise TopologicalError(
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7fd72ad941c0>

**Comment by xinke-wang** [comment]
Hi,
Sorry for the issue, the error seems caused by invalid polygon instances in the LSVT dataset, and the latest image augmentation pipeline of DBNet does not support processing invalid polygons. 

We'll fix this soon. 

Before we can fix the bug, you may would like to try any one of the following solutions for now:
1. Using `poly_make_valid` to convert the invalid polygons to valid ones.
https://github.com/open-mmlab/mmocr/blob/9cfa29f8629fa6684d466a22089c0d5e850fca98/mmocr/core/evaluation/utils.py#L139
2. Filtering invalid samples while converting the annotation files
3. Switch to the legacy ImgAug method.
https://github.com/open-mmlab/mmocr/blob/9cfa29f8629fa6684d466a22089c0d5e850fca98/mmocr/datasets/pipelines/dbnet_transforms.py#L147

**Comment by xinke-wang** [comment]
Hi,
An update here, this issue can be solved by setting `clip_invalid_ploys=False` in `configs/_base_/det_pipelines/dbnet_pipeline.py`. Say if you are training with `train_pipeline_r50dcnv2`, then you have to set the `ImgAug` field as the following to skip the clipping invalid polygon augmentation:

```python
dict(
    type='ImgAug',
    args=[['Fliplr', 0.5],
          dict(cls='Affine', rotate=[-10, 10]), ['Resize', [0.5, 3.0]]],
    clip_invalid_ploys=False)
```

If you have further questions, please feel free to reopen the issue.

**Comment by leolkx** [comment]
Hi, I encountered the same problem when training dbnetpp on totaltext and `clip_invalid_ploys=False` was useless. I prepared the totaltext dataset step by step according to MMOCR documents, but I still encountered this bug. Is there something worg with your script that convert totaltext? I really appreciate your work and it's a pity that I can't train the model on the totaltext. @xinke-wang

**Comment by bd20222** [comment]
When I tried to train my own DBNet++ with a custom dataset, I encountered the same error when specifying `clip_invalid_ploys=True`(the default setting).  The error might be caused by some extreme augmentation conditions. 

I inspected the code and took a look at the original `imgaug` repo, and found a similar issue: [Bug in clip_out_of_image](https://github.com/aleju/imgaug/issues/310).

According to [the reply](https://github.com/aleju/imgaug/issues/310#issuecomment-499524376), I remove the invalid polygons before clipping as suggested, the revisited code is something as follows:
```
imgaug_polys = aug.augment_polygons(
                [imgaug.PolygonsOnImage(imgaug_polys, shape=img_shape)]
            )[0]
imgaug_polys.polygons = [poly for poly in imgaug_polys.polygons if poly.is_valid]
imgaug_polys.clip_out_of_image()
``` 
The current codebase is:
[](https://github.com/open-mmlab/mmocr/blob/e2883074d8d7c27e858c6ccbb6b77e7513a28d45/mmocr/datasets/pipelines/dbnet_transforms.py#L133-#L135)

BTW,  setting `clip_invalid_ploys=False` also works well in my case.

**Comment by gaotongxiao** [comment]
Hi @bd20222, thank you for sharing your solution here! It looks promising and we believe it can help many other users. For your contribution to be accredited, would you like to raise a PR for this patch?
