### ISSUE TITLE
Cannot run MASTER model: missing 'n_head'

### ISSUE THREAD

**Issue by davidmasek** [open-mmlab/mmocr#1030]
I am unable to run the newly added MASTER recognition model.

**Checklist**

- [x] I have searched related issues but cannot get the expected help.
- [x] The bug has not been fixed in the latest version.

**Describe the bug**
I am unable to run the newly added MASTER recognition model.

When I create `mmocr.utils.ocr.MMOCR(det=None, recog='MASTER')` I get `FileNotFoundError` about `<path>/mmocr/configs/textrecog/master/master_academic.py` missing. When I specify path to only config I found with `recog_config=<path>/mmocr/configs/textrecog/master/master_r31_12e_ST_MJ_SA.py` I get `TypeError: MASTER: ResNet: __init__() missing 1 required positional argument: 'n_head'`.

**Reproduction**
```
from mmocr.utils.ocr import MMOCR
MMOCR(det=None, recog='MASTER', recog_config='<path>/mmocr/configs/textrecog/master/master_r31_12e_ST_MJ_SA.py')
```

**Environment**
sys.platform: linux
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce MX150
CUDA_HOME: /usr/local/cuda-11.6
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.3
OpenCV: 4.5.4
MMCV: 1.5.1
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMOCR: 0.6.0+13986f4

**Error traceback**
```
Traceback (most recent call last):
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 66, in build_from_cfg
    return obj_cls(**args)
  File "<path>/mmocr/mmocr/models/textrecog/backbones/resnet.py", line 70, in __init__
    res_layer = self._make_layer(
  File "<path>/mmocr/mmocr/models/textrecog/backbones/resnet.py", line 105, in _make_layer
    block(
  File "<path>/mmocr/mmocr/models/textrecog/layers/conv_layer.py", line 78, in __init__
    self.after_conv2_plugin_names = self.make_block_plugins(
  File "<path>/mmocr/mmocr/models/textrecog/layers/conv_layer.py", line 97, in make_block_plugins
    name, layer = build_plugin_layer(
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/bricks/plugin.py", line 87, in build_plugin_layer
    layer = plugin_layer(**kwargs, **cfg_)
TypeError: __init__() missing 1 required positional argument: 'n_head'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 66, in build_from_cfg
    return obj_cls(**args)
  File "<path>/mmocr/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py", line 43, in __init__
    self.backbone = build_backbone(backbone)
  File "<path>/mmocr/mmocr/models/builder.py", line 72, in build_backbone
    return BACKBONES.build(cfg)
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 234, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ResNet: __init__() missing 1 required positional argument: 'n_head'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate_recognizer.py", line 86, in <module>
    ocr = MMOCR(
  File "<path>/mmocr/mmocr/utils/ocr.py", line 411, in __init__
    self.recog_model = init_detector(
  File "<path>/mmocr/mmocr/apis/inference.py", line 43, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "<path>/mmocr/mmocr/models/builder.py", line 151, in build_detector
    return DETECTORS.build(
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 234, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "<path>/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MASTER: ResNet: __init__() missing 1 required positional argument: 'n_head'
```
I replaced paths to home with `<path>`.

Thank you for any help.

**Comment by Mountchicken** [comment]
Hi @davidmasek 
- Thanks to point it out. One param's name in the config file is wrong.
- Replace `headers` with `n_head` will solve this problem.
https://github.com/open-mmlab/mmocr/blob/13986f497de938cae957e9863851e7f49ccdbe6d/configs/_base_/recog_models/master.py#L14-L18
