### ISSUE TITLE
Getting TypeError: cannot pickle 'module' object

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1053]
**Describe the bug**
Compiler return

``TypeError: cannot pickle 'module' object`
`

**Reproduction**

In general,
1) The `cfg` file was created and save as `cfg_recog`

```
import os
_base_ = [
    'configs/_base_/default_runtime.py',
    'configs/_base_/recog_models/sar.py',
    'configs/_base_/schedules/schedule_adam_step_5e.py',
    'configs/_base_/recog_pipelines/sar_pipeline.py',
]

dataset_type = 'OCRDataset'

# Location where the annotation and crop images are being stored
root='tests/data/ocr_toy_dataset'


img_prefix =os.path.join(root,'imgs')


train_anno_file1 = os.path.join(root,'label.txt')



train_datasets1 = dict(
    type='OCRDataset',
    img_prefix=img_prefix,
    ann_file=train_anno_file1,
    loader=dict(
        type='AnnFileLoader',
        repeat=20,
        file_format='txt',
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)


train_datasets1 = dict(
    type='OCRDataset',
    img_prefix=img_prefix,
    ann_file=train_anno_file1,
    loader=dict(
        type='AnnFileLoader',
        repeat=20,
        file_format='txt',
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)




# For time being, assume the setting for training and validation is the same, though practically we can separate both testing sets



train_list = [train_datasets1]

# For demonstration purpose, we assume the train and validation list is the same
test_list = [train_datasets1]


train_pipeline = {{_base_.train_pipeline}}
test_pipeline = {{_base_.test_pipeline}}

data = dict(
    samples_per_gpu=64,
    workers_per_gpu=2,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='UniformConcatDataset',
        datasets=train_list,
        pipeline=train_pipeline),
    val=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline),
    test=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline))

evaluation = dict(interval=1, metric='acc')
```
2) The `cfg_python` was then call via

```
from mmcv import Config
cfg = Config.fromfile('cfg_recog.py')
```

**Environment**

`Ubuntu 16.04`

**Error traceback**

```
Traceback (most recent call last):
  File root_folder//12b_training_recog.py", line 18, in <module>
    cfg = Config.fromfile('cfg_recog.py')
  File "root_folder/envs/ocr_r/lib/python3.8/site-packages/mmcv/utils/config.py", line 331, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "root_folder/envs/ocr_r/lib/python3.8/site-packages/mmcv/utils/config.py", line 261, in _file2dict
    cfg_dict = Config._substitute_base_vars(cfg_dict, base_var_dict,
  File "root_folder/envs/ocr_r/lib/python3.8/site-packages/mmcv/utils/config.py", line 149, in _substitute_base_vars
    cfg = copy.deepcopy(cfg)
  File "root_folder/envs/ocr_r/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "root_folder/envs/ocr_r/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "root_folder/envs/ocr_r/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object

```

However, executing the same script in Google Colab work flawlessly.  The Google Colab can be found via this [link](https://github.com/balandongiv/mmocr_tutorial/blob/main/how_to_load_base_config.ipynb)

**Comment by balandongiv** [comment]
I think the issue is due to `import os`` in the `cfg_recog`.

Changing

```
img_prefix =os.path.join(root,'imgs')
train_anno_file1 = os.path.join(root,'label.txt')
```

to

```
img_prefix =f'{root}imgs'
train_anno_file1 =f'{root}label.txt'
```
and comment the `import os` alleviate the issue in HPC with ubuntu 16.04.


But, I am still curious why the same issue is not happening when executing the original code in Google Colab

**Comment by Mountchicken** [comment]
Hi @balandongiv 
Can't tell why it works fine on Colab. But the python file of config should never have executable statements like `os.path.join()` as it is required by MMCV's Config

**Comment by balandongiv** [comment]
Thanks for the comment @Mountchicken.
