### ISSUE TITLE
Unexpected EOF error

### ISSUE THREAD

**Issue by liuquande** [open-mmlab/mmocr#1059]
Hi, 

I am trining the use the inference interface of mmocr to detect and recognize the text of an image.
When running the demo inference commond "python mmocr/utils/ocr.py demo/demo_text_ocr.jpg --print-result --imshow", I got an unexpected EOF error "**RuntimeError: unexpected EOF, expected 3536061 more bytes. The file might be corrupted.**".

The output and error information areas follows:
```
# python mmocr/utils/ocr.py demo/demo_text_ocr.jpg --print-result --imshow                                                                                                                         
load checkpoint from http path: https://download.openmmlab.com/mmocr/textdet/panet/panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth                                                                                               
Traceback (most recent call last):                                                                                                                                                                                          
  File "mmocr/utils/ocr.py", line 874, in <module>
    main()
  File "mmocr/utils/ocr.py", line 869, in main
    ocr = MMOCR(**vars(args))
  File "mmocr/utils/ocr.py", line 390, in __init__
    self.detect_model = init_detector(
  File "/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/apis/inference.py", line 45, in init_detector                                                                                                                
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 581, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 520, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 285, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 323, in load_from_http
    checkpoint = load_url(
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/hub.py", line 590, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 3536061 more bytes. The file might be corrupted.

```

Would you please give some hint about the cause of this error?
Many thanks for the help.

Best.

**Comment by liuquande** [comment]
Hi @Mountchicken ,

Many thanks for the replay, I tried to download the model manually and now it works.

But when I using the default model for inference, I found it insensitive to the numbers.

For example in this result, the name of player can be well captured but the numbers (i.e., 23 and 6) cannot, though the numbers are clear.
![image](https://user-images.githubusercontent.com/29408526/172769178-3c64ba0b-192d-4ba8-89f1-e88786fc4243.png)

Would you have some idea of the reason, is this because the numbers are ignored (not labeled) in existing OCR dataset, cause I notice that some datasets ignore words less than three characters.

Besides, may I know which model should I use if I would like to detect some easy numbers ranging from 0 to 99 in the scene?

Many thanks!

Best.

**Comment by Mountchicken** [comment]
Hi @liuquande 
I guess in the training set of ICDAR, there may be fewer images containing numbers, so it leads to a weaker generalization of the model to numbers. Try DBNet, it may work better.

**Comment by liuquande** [comment]
Many thanks for the reply. I shall close the issue then since my question has been well addressed.
