### ISSUE TITLE
Error encountered when using pytorch2onnx.py

### ISSUE THREAD

**Issue by liuquande** [open-mmlab/mmocr#1085]
Hi,

I am trying to use the provided **"pytorch2onnx.py" script to package a recognition model into onnx**, with command of 
```
python pytorch2onnx.py --model_config "./abinet_academic.py" --model_ckpt "./epoch_12.pth" --model_type "recog" --image_path "./demo_imgs/001_2_00042_0.jpg"
```
However, a runtime error is encountered as "**RuntimeError: Expected condition, x and y to be on the same device, but condition is on cuda:0 and x and y are on cuda:0 and cpu respectively**"

The output and error information are as follows:

```
pytorch2onnx.py:336: UserWarning: DeprecationWarning: This tool will be deprecated in future. Welcome to use the unified model deployment toolbox MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
load checkpoint from local path: ./epoch_12.pth
/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/onnx/symbolic.py:481: UserWarning: DeprecationWarning: This function will be deprecated in future. Welcome to use the unified model deployment toolbox MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/models/textrecog/decoders/abinet_language_decoder.py:147: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  out = torch.where(abn, out, out.new_tensor(logit.shape[1]))
Traceback (most recent call last):
  File "pytorch2onnx.py", line 370, in <module>
    main()
  File "pytorch2onnx.py", line 356, in main
    pytorch2onnx(
  File "pytorch2onnx.py", line 194, in pytorch2onnx
    torch.onnx.export(
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/models/textrecog/recognizer/base.py", line 94, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/models/textrecog/recognizer/base.py", line 72, in forward_test
    return self.simple_test(imgs, img_metas, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/models/textrecog/recognizer/abinet.py", line 163, in simple_test
    out_dec = self.decoder(
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/models/textrecog/decoders/base_decoder.py", line 30, in forward
    return self.forward_test(feat, out_enc, img_metas)
  File "/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/models/textrecog/decoders/abinet_language_decoder.py", line 133, in forward_test
    return self.forward_train(feat, out_enc, None, img_metas)
  File "/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/models/textrecog/decoders/abinet_language_decoder.py", line 104, in forward_train
    lengths = self._get_length(logits)
  File "/apdcephfs/share_1041553/qdliu/cv_project/mmcv/mmdetection/mmocr/mmocr/models/textrecog/decoders/abinet_language_decoder.py", line 147, in _get_length
    out = torch.where(abn, out, out.new_tensor(logit.shape[1]))
RuntimeError: Expected condition, x and y to be on the same device, but condition is on cuda:0 and x and y are on cuda:0 and cpu respectively
```

Could you please give me some hint on how to address it ?
Many thanks !

**Best.**

**Comment by gaotongxiao** [comment]
Currently, this script doesn't support exporting ABINet to ONNX. If you feel it would be of great help, please raise the feature request to MMDeploy (https://github.com/open-mmlab/mmdeploy). And your deployment-related issues will be answered there.
