### ISSUE TITLE
Getting RuntimeError and TypeError on diffrent machine for same `cfg` setting

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmocr#1135]
Using a same `config` on two different machines result in two unique issue.

In local machine with `Ubuntu 16.04`, the compiler return the following:

`RuntimeError: ModulatedDeformConv is not compiled with GPU support`

Whereas, in Google Colab, the compiler return
`
TypeError: 'Polygon' object is not iterable`

The config in general are similar, except for the `dir` path.

For example, the `cfg` used in the Google Colab is as follow:

```

_base_ = [
    '/mmocr/configs/_base_/default_runtime.py',
    '/mmocr/configs/_base_/schedules/schedule_sgd_1200e.py',
    '/mmocr/configs/_base_/det_models/dbnetpp_r50dcnv2_fpnc.py',
    '/mmocr/configs/_base_/det_pipelines/dbnet_pipeline.py',
]


root='/mmocr/resources'

work_dir ='/mmocr/resources/train_detect'
root = '/mmocr/tests/data/toy_dataset'


test = dict(
    type='TextDetDataset',
    img_prefix=f'{root}/imgs',
    ann_file=f'{root}/instances_test.txt',
    loader=dict(
        type='AnnFileLoader',
        repeat=1,
        file_format='txt',
        parser=dict(
            type='LineJsonParser',
            keys=['file_name', 'height', 'width', 'annotations'])),
    pipeline=None,
    test_mode=True)

train_list =[test]
test_list = [test]


train_pipeline_r50dcnv2 = {{_base_.train_pipeline_r50dcnv2}}
test_pipeline_4068_1024 = {{_base_.test_pipeline_4068_1024}}


data = dict(
    samples_per_gpu=4, # Default 32
    workers_per_gpu=4,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='UniformConcatDataset',
        datasets=train_list,
        pipeline=train_pipeline_r50dcnv2),
    val=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline_4068_1024),
    test=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline_4068_1024))

evaluation = dict(
    interval=100,
    metric='hmean-iou')
```

The full traceback

In Local machine:

```
2022-07-02 21:27:27,169 - mmocr - INFO - workflow: [('train', 1)], max: 1200 epochs
2022-07-02 21:27:27,169 - mmocr - INFO - Checkpoints will be saved to /user/anaconda3/resources/dlib/resources/train_detect by HardDiskBackend.
Traceback (most recent call last):
  File "/user/anaconda3/resources/dlib/12b_training_recog.py", line 52, in <module>
    train_detector(model, datasets, cfg, distributed=False, validate=True)
  File "/user/anaconda3/resources/dlib/mmocr/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/user/anaconda3/resources/dlib/mmocr/models/textdet/detectors/single_stage_text_detector.py", line 36, in forward_train
    x = self.extract_feat(img)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 43, in extract_feat
    x = self.backbone(img)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 643, in forward
    x = res_layer(x)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 298, in forward
    out = _inner_forward(x)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 275, in _inner_forward
    out = self.conv2(out)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmcv/ops/modulated_deform_conv.py", line 251, in forward
    return modulated_deform_conv2d(x, offset, mask, self.weight, self.bias,
  File "/user/anaconda3/envs/ocr_r/lib/python3.8/site-packages/mmcv/ops/modulated_deform_conv.py", line 73, in forward
    ext_module.modulated_deform_conv_forward(
RuntimeError: ModulatedDeformConv is not compiled with GPU support

Process finished with exit code 1
```

The full traceback in Google Colab

```
2022-07-02 13:47:11,677 - mmocr - INFO - workflow: [('train', 1)], max: 1200 epochs
2022-07-02 13:47:11,683 - mmocr - INFO - Checkpoints will be saved to /mmocr/resources/train_detect by HardDiskBackend.

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-13-7d556c238058>](https://localhost:8080/#) in <module>()
     36 # # Create work_dir
     37 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 38 train_detector(model, datasets, cfg, distributed=False, validate=True)

6 frames

[/usr/local/lib/python3.7/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    455             # instantiate since we don't know how to
    456             raise RuntimeError(msg) from None
--> 457         raise exception
    458 
    459 

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py", line 416, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/mmocr/mmocr/datasets/base_dataset.py", line 139, in __getitem__
    return self.prepare_test_img(index)
  File "/mmocr/mmocr/datasets/base_dataset.py", line 111, in prepare_test_img
    return self.prepare_train_img(img_info)
  File "/mmocr/mmocr/datasets/text_det_dataset.py", line 78, in prepare_train_img
    return self.pipeline(results)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/mmocr/mmocr/datasets/pipelines/dbnet_transforms.py", line 83, in __call__
    self.may_augment_annotation(aug, shape, target_shape, results)
  File "/mmocr/mmocr/datasets/pipelines/dbnet_transforms.py", line 94, in may_augment_annotation
    masks = self.may_augment_poly(aug, shape, results[key])
  File "/mmocr/mmocr/datasets/pipelines/dbnet_transforms.py", line 140, in may_augment_poly
    for point in poly:
TypeError: 'Polygon' object is not iterable
```

The Google Colab Notebook can be accessed via the following [link](https://github.com/balandongiv/mmocr_tutorial/blob/main/ISSUE_RuntimeError_and_TypeError.ipynb)

The `cfg` can be downloaded via the [link](https://drive.google.com/file/d/1bsEhczfLa5ydltg_oIU3nLOykxCgupQU/view)

**Comment by xinke-wang** [comment]
Did you install the GPU-compiled `mmcv-full` on your local machine? Please check the [install guide](https://github.com/open-mmlab/mmcv). 
```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html
```

**Comment by balandongiv** [comment]
Hi @xinke-wang , I believe I had install the `mmcv-full` properly as I am able perform text recognition without any problem on my local machine. The `RuntimeError: ModulatedDeformConv is not compiled with GPU support` only occur when I train the text detection model.
