### ISSUE TITLE
cannot debug using vscode

### ISSUE THREAD

**Issue by jeffreykuang** [open-mmlab/mmocr#126]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I debug the tools/test.py using the following config

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "test_panet",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": ["configs/textdet/panet/panet_r18_fpem_ffm_600e_icdar2015.py",
                "checkpoints/panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth",
                "--show-dir",
                "work_dir/"],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

and get the following errors:

```bash
(base) SENSETIME\kuangzhh@hk0014000424l:~/code/github/mmocr-1$  env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/bin/python /home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 36283 /home/SENSETIME/kuangzhh/code/github/mmocr-1/tools/test.py configs/textdet/panet/panet_r18_fpem_ffm_600e_icdar2015.py checkpoints/panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth --show-dir work_dir/ 
source /home/SENSETIME/kuangzhh/anaconda3/bin/activate
conda activate open-mmlab
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
Use load_from_local loader
[                                                  ] 0/500, elapsed: 0s, ETA:E00016.895: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/contextlib.py", line 112, in __enter__
                return next(self.gen)
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/SENSETIME/kuangzhh/code/github/mmocr-1/tools/test.py", line 216, in <module>
    main()
  File "/home/SENSETIME/kuangzhh/code/github/mmocr-1/tools/test.py", line 186, in main
    args.show_score_thr)
  File "/home/SENSETIME/kuangzhh/code/mmdetection/mmdet/apis/test.py", line 25, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
E00016.901: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/contextlib.py", line 112, in __enter__
                return next(self.gen)
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/SENSETIME/kuangzhh/code/github/mmocr-1/tools/test.py", line 216, in <module>
    main()
  File "/home/SENSETIME/kuangzhh/code/github/mmocr-1/tools/test.py", line 186, in main
    args.show_score_thr)
  File "/home/SENSETIME/kuangzhh/code/mmdetection/mmdet/apis/test.py", line 25, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
      File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
self._launch(process_obj)
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 528, in new_fork
    self.pid = os.fork()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 528, in new_fork
    _on_forked_process()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 50, in _on_forked_process
    pydevd.settrace_forked()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 2427, in settrace_forked
    _on_forked_process()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py", line 50, in _on_forked_process
    pydevd.settrace_forked()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 2427, in settrace_forked
    patch_multiprocessing=True,
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1060, in connect
    s = start_client(host, port)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 136, in _start_client
    return start_client(daemon, h, p)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
    return f(*args, **kwargs)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 74, in start_client
    sock, start_session = daemon.start_client((host, port))
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 214, in start_client
    with self.started():
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 110, in started
    self.start()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
    raise RuntimeError('already started')
RuntimeError: already started
    patch_multiprocessing=True,
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 2179, in settrace
    wait_for_ready_to_run,
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 2230, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1060, in connect
    s = start_client(host, port)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 136, in _start_client
    return start_client(daemon, h, p)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/log.py", line 110, in g
    return f(*args, **kwargs)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/pydevd_hooks.py", line 74, in start_client
    sock, start_session = daemon.start_client((host, port))
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 214, in start_client
    with self.started():
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 110, in started
    self.start()
  File "/home/SENSETIME/kuangzhh/.vscode/extensions/ms-python.python-2020.5.86806/pythonFiles/lib/python/old_ptvsd/ptvsd/daemon.py", line 145, in start
    raise RuntimeError('already started')
RuntimeError: already started
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/util.py", line 334, in _exit_function
    p.join()
  File "/home/SENSETIME/kuangzhh/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Terminated
```

**Comment by innerlee** [comment]
This might be caused by multithreading. The first thing to try is to set the workers_per_gpu to 0

**Comment by jeffreykuang** [comment]
fix this issue via setting the worker_per_gpu to 0 in the config
