### ISSUE TITLE
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' 

### ISSUE THREAD

**Issue by ZhangXinNan** [open-mmlab/mmocr#1304]
```
(open-mmlab) ➜  mmocr git:(zxdev) python mmocr/utils/ocr.py demo/demo_text_ocr.jpg --print-result --imshow                 
No CUDA runtime is found, using CUDA_HOME='/usr'
Traceback (most recent call last):
  File "mmocr/utils/ocr.py", line 13, in <module>
    from mmcv.runner import load_checkpoint
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/__init__.py", line 3, in <module>
    from .base_runner import BaseRunner
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 17, in <module>
    from .checkpoint import load_checkpoint
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 17, in <module>
    import torchvision
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/home/zhangxin/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/PIL/__init__.py)
```

**Comment by ZhangXinNan** [comment]
在~/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/PIL/__init__.py里
```python
from . import _version

# VERSION was removed in Pillow 6.0.0.
# PILLOW_VERSION was removed in Pillow 9.0.0.
# Use __version__ instead.
__version__ = _version.__version__
del _version
```
这里提示9.0.0之后已经去掉了PILLOW_VERSION，而在torchvision中仍然使用到了，我想问是在哪一步安装时没有指定PIL的版本导致此问题的。

**Comment by gaotongxiao** [comment]
Looks like your pillow is not compatible with torchvision. Try reinstalling torchvision may fix it.
