### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by vahuja4** [open-mmlab/mmocr#1328]
I pip installed mmdet and mmocr successfully, but when I ran the command to download the checkpoints, here is the error I got:

`root@89e7fa9d29bc:~# mim download mmocr --config dbnet_r18_fpnc_1200e_icdar2015 --dest .
Traceback (most recent call last):
  File "/opt/conda/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mim/commands/download.py", line 49, in cli
    download(package, configs, dest_root)
  File "/opt/conda/lib/python3.8/site-packages/mim/commands/download.py", line 89, in download
    from mmcv import Config
  File "/opt/conda/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/opt/conda/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/opt/conda/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 41, in <module>
    from .env import collect_env
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
root@89e7fa9d29bc:~# mim download mmocr --config crnn_academic_dataset --dest .
Traceback (most recent call last):
  File "/opt/conda/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mim/commands/download.py", line 49, in cli
    download(package, configs, dest_root)
  File "/opt/conda/lib/python3.8/site-packages/mim/commands/download.py", line 89, in download
    from mmcv import Config
  File "/opt/conda/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/opt/conda/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/opt/conda/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 41, in <module>
    from .env import collect_env
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)`

**Comment by gaotongxiao** [comment]
Is it an issue of MIM? @zhouzaida

**Comment by zhouzaida** [comment]
Hi @vahuja4 , what is your opencv-python version?
