### ISSUE TITLE
Error when training DBNetpp with fp16

### ISSUE THREAD

**Issue by Hugotong6425** [open-mmlab/mmocr#1375]
config (i.e. `dbnetpp_r50dcnv2_fpnc_1200e_icdar2015.py`):
```
_base_ = [
    '../../_base_/default_runtime.py',
    '../../_base_/schedules/schedule_sgd_1200e.py',
    '../../_base_/det_models/dbnetpp_r50dcnv2_fpnc.py',
    '../../_base_/det_datasets/icdar2015.py',
    '../../_base_/det_pipelines/dbnet_pipeline.py'
]

train_list = {{_base_.train_list}}
test_list = {{_base_.test_list}}

train_pipeline_r50dcnv2 = {{_base_.train_pipeline_r50dcnv2}}
test_pipeline_4068_1024 = {{_base_.test_pipeline_4068_1024}}

load_from = 'checkpoints/textdet/dbnetpp/res50dcnv2_synthtext.pth'

fp16 = dict(loss_scale=512.)

data = dict(
    samples_per_gpu=12,
    workers_per_gpu=8,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='UniformConcatDataset',
        datasets=train_list,
        pipeline=train_pipeline_r50dcnv2),
    val=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        show_mean_scores=True,
        pipeline=test_pipeline_4068_1024),
    test=dict(
        type='UniformConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline_4068_1024))

```

training script:
```
python tools/train.py \
    ./configs/textdet/dbnetpp/dbnetpp_r50dcnv2_fpnc_1200e_icdar2015.py \
    --load-from ./pretrained_weights/dbnetpp_r50dcnv2_fpnc_100k_iter_synthtext-20220502-db297554.pth \
    --gpu-id 0 \
    --seed 0 \
    --work-dir ./work_dirs/testing
```

error log:
```
Traceback (most recent call last):
  File "tools/train.py", line 230, in <module>
    main()
  File "tools/train.py", line 226, in main
    meta=meta)
  File "/home/carpark-research/mmocr/mmocr/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 146, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/carpark-research/mmocr/mmocr/models/textdet/detectors/single_stage_text_detector.py", line 38, in forward_train
    losses = self.bbox_head.loss(preds, **kwargs)
  File "/home/carpark-research/mmocr/mmocr/models/textdet/dense_heads/head_mixin.py", line 89, in loss
    losses = self.loss_module(pred_maps, self.downsample_ratio, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/carpark-research/mmocr/mmocr/models/textdet/losses/db_loss.py", line 150, in forward
    gt['gt_shrink_mask'][0])
  File "/home/carpark-research/mmocr/mmocr/models/textdet/losses/db_loss.py", line 91, in balance_bce_loss
    loss = F.binary_cross_entropy(pred, gt, reduction='none')
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 3065, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: torch.nn.functional.binary_cross_entropy and torch.nn.BCELoss are unsafe to autocast.
Many models use a sigmoid layer right before the binary cross entropy layer.
In this case, combine the two layers using torch.nn.functional.binary_cross_entropy_with_logits
or torch.nn.BCEWithLogitsLoss.  binary_cross_entropy_with_logits and BCEWithLogits are
safe to autocast.
```

Thanks for the help!

**Comment by xinke-wang** [comment]
Hi, as shown in the log, the `BCELoss` used by DBNet++ does not support fp16. If you want to use mixed precision training, you may consider to use the [dev-1.x](https://github.com/open-mmlab/mmocr/tree/dev-1.x) branch, where we have replaced the `BCELoss` with [`BCEWithLogitsLoss`](https://github.com/open-mmlab/mmocr/blob/50cba1ac6ef041bac7a0901f3d551fb6c34a840e/mmocr/models/common/losses/bce_loss.py#L11). Check out [document](https://mmocr.readthedocs.io/en/dev-1.x/user_guides/train_test.html#mixed-precision-training) for more details.
