### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/wildreceipt/dict.txt'

### ISSUE THREAD

**Issue by czb7046** [open-mmlab/mmocr#1405]
when I run “python mmocr/utils/ocr.py demo/demo_kie.jpeg  --det PS_CTW --recog SAR --kie SDMGR --print-result --imshow”,the error happens:
d:\program files\pycharmworkspace\pytorchworkspace\east\mmocr\mmocr\datasets\kie_dataset.py:43: UserWarning: KIEDataset is only initialized as a downstream demo task of text detection and recognition without an annotation file.
  warnings.warn(
Traceback (most recent call last):
  File "mmocr/utils/ocr.py", line 878, in <module>
    main()
  File "mmocr/utils/ocr.py", line 874, in main
    ocr.readtext(**vars(args))
  File "mmocr/utils/ocr.py", line 570, in readtext
    det_recog_result = self.det_recog_kie_inference(
  File "mmocr/utils/ocr.py", line 685, in det_recog_kie_inference
    kie_dataset = KIEDataset(
  File "d:\program files\pycharmworkspace\pytorchworkspace\east\mmocr\mmocr\datasets\kie_dataset.py", line 62, in __init__
    for ind, line in enumerate(list_from_file(dict_file), 1)
  File "d:\program files\pycharmworkspace\pytorchworkspace\east\mmocr\mmocr\utils\fileio.py", line 35, in list_from_file
    with open(filename, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/wildreceipt/dict.txt'
  
Where to download this file?

**Comment by xinke-wang** [comment]
Hi, please follow this [instruction](https://mmocr.readthedocs.io/en/latest/datasets/kie.html#preparation-steps) to prepare the wild receipt dataset.

**Comment by czb7046** [comment]
> Hi, please follow this [instruction](https://mmocr.readthedocs.io/en/latest/datasets/kie.html) to prepare the wild receipt dataset.

Thanks
