### ISSUE TITLE
The orc.py can run but failedly debug!

### ISSUE THREAD

**Issue by czb7046** [open-mmlab/mmocr#1408]
**The Failed Info as follows:**
Connected to pydev debugger (build 183.5912.18)
D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "D:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Program Files/PyCharmWorkspace/pytorchworkspace/EAST/mmocr/mmocr/utils/ocr.py", line 9, in <module>
    import mmcv
  File "D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\__init__.py", line 3, in <module>
    from .arraymisc import *
  File "D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\arraymisc\__init__.py", line 2, in <module>
    from .quantization import dequantize, quantize
  File "D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\arraymisc\quantization.py", line 4, in <module>
    import numpy as np
  File "D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "D:\ProgramFiles\Anaconda3\envs\openmmlab\lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "D:\ProgramFiles\Anaconda3\envs\openmmlab\python.exe"
  * The NumPy version is: "1.23.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath:

**Comment by czb7046** [comment]
It's solved by:
pip uninstall -y numpy
pip uninstall -y setuptools
pip install setuptoools
pip install numpy
