### ISSUE TITLE
[Bug] offline_eval error and incorrect behaviour

### ISSUE THREAD

**Issue by rogachevai** [open-mmlab/mmocr#1496]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmocr/tree/dev-1.x

### Environment

Official Docker

### Reproduces the problem - code sample

```shell
ython tools/test.py configs/textdet/panet/panet_resnet18_fpem-ffm_600e_ctw1500.py weights/panet_resnet18_fpem-ffm_600e_ctw1500_20220826_144818-980f32d0.pth --save-preds
```

### Reproduces the problem - command or script

```shell
python tools/analysis_tools/offline_eval.py configs/textdet/panet/panet_resnet18_fpem-ffm_600e_ctw1500.py work_dirs/panet_resnet18_fpem-ffm_600e_ctw1500/panet_resnet18_fpem-ffm_600e_ctw1500_20220826_144818-980f32d0.pth_predictions.pkl
```

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/analysis_tools/offline_eval_fix.py", line 78, in <module>
    main()
  File "tools/analysis_tools/offline_eval_fix.py", line 73, in main
    eval_results = evaluator.offline_evaluate(dataset, predictions)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/evaluator/evaluator.py", line 133, in offline_evaluate
    self.process(output_chunk, data_chunk)
  File "tools/analysis_tools/offline_eval_fix.py", line 36, in process
    metric.process([], _data_samples)
  File "/home/experiments/tasks/CVIZ-2259-STR/mmocr/mmocr/evaluation/metrics/hmean_iou_metric.py", line 94, in process
    pred_polygons = pred_instances.get('polygons')
AttributeError: 'NoneType' object has no attribute 'get'

### Additional information

1. I want to get offline metrics
2. I used official script for CTW1500
3. It fails as it looks like in   https://github.com/open-mmlab/mmocr/blob/357ccaf27daf6897561bde820e0565c5eb1440da/tools/analysis_tools/offline_eval.py#L48
two variables should be moved to each one's place according to the docstring like this:
```python
eval_results = evaluator.offline_evaluate(predictions, dataset)
```
However at this point I face another issue:
Traceback (most recent call last):
  File "tools/analysis_tools/offline_eval.py", line 53, in <module>
    main()
  File "tools/analysis_tools/offline_eval.py", line 48, in main
    eval_results = evaluator.offline_evaluate(predictions, dataset)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/evaluator/evaluator.py", line 129, in offline_evaluate
    data_chunk = pseudo_collate(data[size:size + chunk_size])
  File "/opt/conda/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 401, in __getitem__
    data = self.prepare_data(idx)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 788, in prepare_data
    data_info = self.get_data_info(idx)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 111, in wrapper
    return old_func(obj, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 261, in get_data_info
    start_addr = 0 if idx == 0 else self.data_address[idx - 1].item()
TypeError: unsupported operand type(s) for -: 'slice' and 'int'

I tried to replace this line (https://github.com/open-mmlab/mmengine/blob/bf369da22ada3336e8f44e23c7de3f3117b9c84a/mmengine/evaluator/evaluator.py#L53) with 
```python
for data_sample in data_batch:
```
but it leads to the fact that https://github.com/open-mmlab/mmocr/blob/1.x/mmocr/evaluation/metrics/hmean_iou_metric.py can not properly treat chunks of size 1.

**Comment by gaotongxiao** [comment]
Thanks for reporting this issue! It is fixed in https://github.com/open-mmlab/mmocr/pull/1500/files, you are welcome to try & review this patch :)
