### ISSUE TITLE
[Bug]  inconsistent device between input and model 

### ISSUE THREAD

**Issue by XWHtorrentx** [open-mmlab/mmocr#1572]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

TorchVision: 0.14.0
OpenCV: 4.6.0
MMCV: 1.7.0
MMCV Compiler: clang 13.1.6
MMCV CUDA Compiler: not available
MMOCR: 0.6.3+a4fe6bb
Platform: Apple M1 Pro, macOS 13.0.1 (22A400)

### Reproduces the problem - code sample

`from mmocr.utils.ocr import MMOCR`
`mmocr = MMOCR(det=None, recog='SAR',device='mps')`
`mmocr.readtext('demo/demo_text_recog.jpg', print_result=True, output='outputs/demo_text_recog_pred.jpg')`

### Reproduces the problem - command or script

python

### Reproduces the problem - error message

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mmocr/mmocr/utils/ocr.py", line 576, in readtext
    result = self.single_inference(model, args.arrays.to(self.device),
  File "mmocr/mmocr/utils/ocr.py", line 808, in single_inference
    result.append(inference(model, arr, batch_mode=False))
  File "mmocr/mmocr/utils/ocr.py", line 793, in inference
    return model_inference(m, a, **kwargs)
  File "mmocr/mmocr/apis/inference.py", line 185, in model_inference
    results = model(return_loss=False, rescale=True, **data)
  File "miniforge3/envs/mmocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "miniforge3/envs/mmocr/lib/python3.10/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "mmocr/mmocr/models/textrecog/recognizer/base.py", line 94, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "mmocr/mmocr/models/textrecog/recognizer/base.py", line 70, in forward_test
    return self.aug_test(imgs, img_metas, **kwargs)
  File "mmocr/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py", line 180, in aug_test
    result = self.simple_test(img, img_meta, **kwargs)
  File "mmocr/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py", line 135, in simple_test
    feat = self.extract_feat(img)
  File "mmocr/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py", line 77, in extract_feat
    x = self.backbone(img)
  File "miniforge3/envs/mmocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "mmocr/mmocr/models/textrecog/backbones/resnet31_ocr.py", line 116, in forward
    x = self.conv1_1(x)
  File "miniforge3/envs/mmocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "miniforge3/envs/mmocr/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "miniforge3/envs/mmocr/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: slow_conv2d_forward_mps: input(device='cpu') and weight(device=mps:0')  must be on the same device

**Comment by Harold-lkk** [comment]
Thanks for your report!  The master branch in MMOCR does not support inference on 'mps' because of the implementation in https://github.com/open-mmlab/mmocr/blob/a4fe6bb67f066bbb5023e38d404c1210b1b3bab2/mmocr/apis/inference.py#L174, where limits the device on GPU and CPU.

Welcome to using dev-1.x for 'MPS'!
