### ISSUE TITLE
Fine Tuning on Custom Dataset: self.train_loop._epoch = checkpoint['meta']['epoch'] KeyError: 'epoch'

### ISSUE THREAD

**Issue by f-izzat** [open-mmlab/mmocr#1715]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmocr/tree/dev-1.x

### Environment

```
openmim                  0.3.5
mmcv                     2.0.0rc4
mmdet                    3.0.0rc5
mmengine                 0.5.0
mmocr                    1.0.0rc5
```

### Reproduces the problem - code sample

Im using absolute paths and it works if im not using the pretrained model checkpoint
Im trying to use svtr on my custom dataset so my config files looks like:
**default_runtime**
```
default_scope = 'mmocr'
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'),
)
randomness = dict(seed=None)

default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=100),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=1),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    sync_buffer=dict(type='SyncBuffersHook'),
    visualization=dict(
        type='VisualizationHook',
        interval=1,
        enable=False,
        show=False,
        draw_gt=False,
        draw_pred=False),
)
# Logging
log_level = 'INFO'
log_processor = dict(type='LogProcessor', window_size=10, by_epoch=True)

load_from = "/Users/faiz/Desktop/CODE/computer_vision/text_detection/TEXT_RECOGNITION/configs/_base_/datasets/svtr-base_20e_st_mj-ea500101.pth"
resume = True

# Evaluation
val_evaluator = dict(
    type='MultiDatasetsEvaluator',
    metrics=[
        dict(
            type='WordMetric',
            mode=['exact', 'ignore_case', 'ignore_case_symbol']),
        dict(type='CharMetric')
    ],
    dataset_prefixes=None)
test_evaluator = val_evaluator

# Visualization
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='TextRecogLocalVisualizer',
    name='visualizer',
    vis_backends=vis_backends)

```

**Config file**
```
_base_ = [
    '/Users/faiz/Desktop/CODE/computer_vision/text_detection/TEXT_RECOGNITION/configs/EXP1/_base_svtr-tiny.py',
    '/Users/faiz/Desktop/CODE/computer_vision/text_detection/TEXT_RECOGNITION/configs/_base_/datasets/dataset_npwp.py',
    '/Users/faiz/Desktop/CODE/computer_vision/text_detection/TEXT_RECOGNITION/configs/_base_/default_runtime.py',
    '/Users/faiz/Desktop/CODE/computer_vision/text_detection/TEXT_RECOGNITION/configs/_base_/schedules/schedule_adam_base.py'
    
]

train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=20, val_interval=1)

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW',
        lr=5 / (10**4) * 2048 / 2048,
        betas=(0.9, 0.99),
        eps=8e-8,
        weight_decay=0.05))

param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.5,
        end_factor=1.,
        end=2,
        verbose=False,
        convert_to_iter_based=True),
    dict(
        type='CosineAnnealingLR',
        T_max=19,
        begin=2,
        end=20,
        verbose=False,
        convert_to_iter_based=True),
]

file_client_args = dict(backend='disk')

train_pipeline = [
    dict(
        type='LoadImageFromFile',
        file_client_args=file_client_args,
        ignore_empty=True,
        min_size=5),
    dict(type='LoadOCRAnnotations', with_text=True),
    dict(
        type='RandomApply',
        prob=0.4,
        transforms=[
            dict(type='TextRecogGeneralAug', ),
        ],
    ),
    dict(
        type='RandomApply',
        prob=0.4,
        transforms=[
            dict(type='CropHeight', ),
        ],
    ),
    dict(
        type='ConditionApply',
        condition='min(results["img_shape"])>10',
        true_transforms=dict(
            type='RandomApply',
            prob=0.4,
            transforms=[
                dict(
                    type='TorchVisionWrapper',
                    op='GaussianBlur',
                    kernel_size=5,
                    sigma=1,
                ),
            ],
        )),
    dict(
        type='RandomApply',
        prob=0.4,
        transforms=[
            dict(
                type='TorchVisionWrapper',
                op='ColorJitter',
                brightness=0.5,
                saturation=0.5,
                contrast=0.5,
                hue=0.1),
        ]),
    dict(
        type='RandomApply',
        prob=0.4,
        transforms=[
            dict(type='ImageContentJitter', ),
        ],
    ),
    dict(
        type='RandomApply',
        prob=0.4,
        transforms=[
            dict(
                type='ImgAugWrapper',
                args=[dict(cls='AdditiveGaussianNoise', scale=0.1**0.5)]),
        ],
    ),
    dict(
        type='RandomApply',
        prob=0.4,
        transforms=[
            dict(type='ReversePixels', ),
        ],
    ),
    dict(type='Resize', scale=(256, 64)),
    dict(
        type='PackTextRecogInputs',
        meta_keys=('img_path', 'ori_shape', 'img_shape', 'valid_ratio'))
]

test_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=file_client_args),
    dict(type='Resize', scale=(256, 64)),
    dict(type='LoadOCRAnnotations', with_text=True),
    dict(
        type='PackTextRecogInputs',
        meta_keys=('img_path', 'ori_shape', 'img_shape', 'valid_ratio'))
]

model = dict(
    preprocessor=dict(output_image_size=(48, 160), ),
    encoder=dict(
        img_size=[48, 160],
        max_seq_len=40,
        out_channels=256,
        embed_dims=[128, 256, 384],
        depth=[3, 6, 9],
        num_heads=[4, 8, 12],
        mixer_types=['Local'] * 8 + ['Global'] * 10),
    decoder=dict(in_channels=256))

# train_dataloader = dict(batch_size=256, )

# dataset settings
textrecog_train = _base_.npwp_textrecog_train
textrecog_test = _base_.npwp_textrecog_test
textrecog_train.pipeline = train_pipeline
textrecog_test.pipeline = test_pipeline


train_dataloader = dict(
    batch_size=256,
    num_workers=2,
    pin_memory=True,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=textrecog_train)

val_dataloader = dict(
    batch_size=1,
    num_workers=1,
    pin_memory=True,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=textrecog_test)

test_dataloader = val_dataloader
```

### Reproduces the problem - command or script

train.py

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/Users/faiz/Desktop/CODE/GIT/mmocr/tools/train.py", line 117, in <module>
    main()
  File "/Users/faiz/Desktop/CODE/GIT/mmocr/tools/train.py", line 113, in main
    runner.train()
  File "/Users/faiz/Desktop/CODE/venvs/text_detection/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1678, in train
    self.load_or_resume()
  File "/Users/faiz/Desktop/CODE/venvs/text_detection/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1624, in load_or_resume
    self.resume(resume_from)
  File "/Users/faiz/Desktop/CODE/venvs/text_detection/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1931, in resume
    self.train_loop._epoch = checkpoint['meta']['epoch']
KeyError: 'epoch'

```

### Additional information

For both text detection and recognition whenever I try to retrain from the pretrained model checkpoint
the error (and yes in the `default_runtime.py` file i placed the path to the checkpoint at `load_from=.....` with `resume=True`)
```
self.train_loop._epoch = checkpoint['meta']['epoch'] KeyError: 'epoch'
```
always occurs.

Is this a problem with a version mismatch?
However, if i train a model without the pretrained checkpoint and instead use an epoch checkpoint everything works fine

**Comment by gaotongxiao** [comment]
It's because the pretrained checkpoints are published without meta records. To start fine-tuning from the pretrained checkpoints, you can set `resume = False` to circumvent this issue (https://mmocr.readthedocs.io/en/dev-1.x/user_guides/config.html#checkpoint-loading-configuration)

We can add a fallback logic for this case to MMEngine @zhouzaida

**Comment by f-izzat** [comment]
Thanks, it works now! Closing the issue
