### ISSUE TITLE
AttributeError: 'TextDetDataSample' object has no attribute 'scale_factor'

### ISSUE THREAD

**Issue by yCobanoglu** [open-mmlab/mmocr#1725]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmocr/tree/dev-1.x

### Environment

`shell
sys.platform: linux
Python: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
CUDA available: False
numpy_random_seed: 2147483648
GCC: gcc (GCC) 12.2.0
PyTorch: 1.13.1+cpu
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cpu
OpenCV: 4.7.0
MMEngine: 0.5.0
MMOCR: 1.0.0rc5+a644c85
`

### Reproduces the problem - code sample

`python3 mmocr_tools/train.py  configs/textdet/textsnake/textsnake_resnet50-oclip_fpn-unet_1200e_icdar2015.py`

### Reproduces the problem - command or script

`python3 mmocr_tools/train.py  configs/textdet/textsnake/textsnake_resnet50-oclip_fpn-unet_1200e_icdar2015.py`

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/cuneiform_sign_detection/mmocr_tools/train.py", line 119, in <module>
    main()
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/cuneiform_sign_detection/mmocr_tools/train.py", line 115, in main
    runner.train()
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmengine/runner/loops.py", line 96, in run
    self.runner.val_loop.run()
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmengine/runner/loops.py", line 347, in run
    self.run_iter(idx, data_batch)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmengine/runner/loops.py", line 367, in run_iter
    outputs = self.runner.model.val_step(data_batch)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 133, in val_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmocr/models/textdet/detectors/base.py", line 74, in forward
    return self.predict(inputs, data_samples)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmocr/models/textdet/detectors/single_stage_text_detector.py", line 107, in predict
    return self.det_head.predict(x, data_samples)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmocr/models/textdet/heads/base.py", line 132, in predict
    predictions = self.postprocessor(outs, data_samples)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmocr/models/textdet/postprocessors/base.py", line 64, in __call__
    results = list(map(process_single, pred_results, data_samples))
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.10/site-packages/mmocr/models/textdet/postprocessors/base.py", line 85, in _process_single
    results = self.rescale(results, data_sample.scale_factor)
AttributeError: 'TextDetDataSample' object has no attribute 'scale_factor'
```

### Additional information
I used one! sample for test and training from mini_icdar2015 dataset from mmocr website.

**Comment by yCobanoglu** [comment]
adding `meta_keys=('img_path', 'ori_shape', 'img_shape', 'scale_factor'))` to line 71 of `_base_textsnake_resnet50_fpn-unet.py` in configs.
