### ISSUE TITLE
[Bug] ImportError: DLL load failed while importing _ext: 找不到指定的模块。

### ISSUE THREAD

**Issue by czb7046** [open-mmlab/mmocr#1872]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

sys.platform: win32
Python: 3.8.15 (default, Nov 11 2022, 08:16:59) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: None
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32215 版
GCC: n/a
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,cod
e=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG
 -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, US
E_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.3
OpenCV: 4.7.0
MMEngine: 0.7.2
MMOCR: 1.0.0+d7c59f3

### Reproduces the problem - code sample

when you debug the script tools\infer.py in pycharm, the error happens, but it's fine to run the script in command line. the virtual python environments is the same.

### Reproduces the problem - command or script

(open-mmlab) F:\ProgramData\webstormspace\mmocr>python tools\infer.py czb\010.jpg --det DBNet --rec SAR --show

### Reproduces the problem - error message

D:\ProgramFiles\Anaconda3\envs\open-mmlab\python.exe F:/ProgramData/webstormspace/mmocr/czb/infer.py
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_resnet50-oclip_1200e_icdar2015/dbnet_resnet50-oclip_1200e_icdar2015_20221102_115917-bde8c87a.pth
Traceback (most recent call last):
  File "F:/ProgramData/webstormspace/mmocr/czb/infer.py", line 2, in <module>
    ocr = MMOCRInferencer(det='DBNet', rec='SAR')
  File "F:\ProgramData\webstormspace\mmocr\mmocr\apis\inferencers\mmocr_inferencer.py", line 69, in __init__
    self.textdet_inferencer = TextDetInferencer(
  File "F:\ProgramData\webstormspace\mmocr\mmocr\apis\inferencers\base_mmocr_inferencer.py", line 65, in __init__
    super().__init__(
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\infer\infer.py", line 176, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\infer\infer.py", line 477, in _init_model
    model = MODELS.build(cfg.model)
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\registry\registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\registry\build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\registry\build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\registry\registry.py", line 442, in get
    self.import_from_location()
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmengine\registry\registry.py", line 376, in import_from_location
    import_module(loc)
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\ProgramData\webstormspace\mmocr\mmocr\models\__init__.py", line 2, in <module>
    from .common import *  # NOQA
  File "F:\ProgramData\webstormspace\mmocr\mmocr\models\common\__init__.py", line 2, in <module>
    from .backbones import *  # NOQA
  File "F:\ProgramData\webstormspace\mmocr\mmocr\models\common\backbones\__init__.py", line 2, in <module>
    from .clip_resnet import CLIPResNet
  File "F:\ProgramData\webstormspace\mmocr\mmocr\models\common\backbones\clip_resnet.py", line 4, in <module>
    from mmdet.models.backbones import ResNet
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\backbones\__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\backbones\csp_darknet.py", line 11, in <module>
    from ..layers import CSPLayer
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\layers\__init__.py", line 3, in <module>
    from .bbox_nms import fast_nms, multiclass_nms
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\layers\bbox_nms.py", line 5, in <module>
    from mmcv.ops.nms import batched_nms
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\ProgramFiles\Anaconda3\envs\open-mmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的模块。

Process finished with exit code 1

**Comment by czb7046** [comment]
运行环境是：sys.platform: win32
Python: 3.8.15 (default, Nov 11 2022, 08:16:59) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: None
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32215 版
GCC: n/a
PyTorch: 1.10.2
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,cod
e=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG
 -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, US
E_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.3
OpenCV: 4.7.0
MMEngine: 0.7.2
MMOCR: 1.0.0+d7c59f3

**Comment by SmileMood** [comment]
> Seems `mmcv` has not been installed correctly, you may try reinstalling it and run your command again:
> 
> ```shell
> pip uninstall mmcv
> pip uninstall mmcv-full
> pip install openmim
> mim install mmcv
> I try it,but still show ModuleNotFoundError: No module named 'mmcv'

**Comment by SmileMood** [comment]
> Seems `mmcv` has not been installed correctly, you may try reinstalling it and run your command again:
> 
> ```shell
> pip uninstall mmcv
> pip uninstall mmcv-full
> pip install openmim
> mim install mmcv
> ```

I try it,but still show ModuleNotFoundError: No module named 'mmcv'

**Comment by worldofzeroandone** [comment]
I also have this problem,I don't know how to handle it,do you handle it?
