### ISSUE TITLE
[Bug] MMOCRInferencer not returning bounding boxes, just polygon

### ISSUE THREAD

**Issue by mdable2** [open-mmlab/mmocr#1887]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

sys.platform: win32
Python: 3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit (AMD64)]
CUDA available: False
numpy_random_seed: 2147483648
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30148 for x64
GCC: n/a
PyTorch: 1.13.1+cpu
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)     
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1+cpu
OpenCV: 4.6.0
MMEngine: 0.7.3
MMOCR: 1.0.0+d7c59f3

### Reproduces the problem - code sample

from mmocr.apis import **MMOCRInferencer**
ocr = MMOCRInferencer(det='MaskRCNN', rec="SAR", device="cpu")
ocr_result = ocr('D:/invoices/US_English_Invoices/imgs/English_Invoice_8-pg_0.png', show=False, print_result=False)
print(ocr_result)
words = ocr_result["predictions"][0]["rec_texts"]
bboxes = ocr_result["predictions"][0]["det_bboxes"]
print(len(words), len(bboxes))

Says no "det_bboxes" key

### Reproduces the problem - command or script

Just running in Jupyter notebook

### Reproduces the problem - error message

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[32], line 4
      2 print(ocr_result)
      3 words = ocr_result["predictions"][0]["rec_texts"]
----> 4 bboxes = ocr_result["predictions"][0]["det_bboxes"]
      5 print(len(words), len(bboxes))
KeyError: 'det_bboxes'

### Additional information

I was following https://mmocr.readthedocs.io/en/latest/get_started/install.html and see there should be a bounding box key for the output.

**Comment by Mountchicken** [comment]
Hi @mdable2 
For text detection, only `det_polygons` and `det_scores` will be returned in Inferencer as shown below.

https://github.com/open-mmlab/mmocr/blob/bbe8964f00c93941546f19929209ff9750b2bf87/mmocr/apis/inferencers/mmocr_inferencer.py#L379-L382

If you want to get the `det_bboxes`, you can implement it with the following code.
```python
from mmocr.utils import poly2bbox
det_bboxes = [poly2bbox(poly.reshape(-1)) for poly in det_polygons]
```

**Comment by rainbow-jay** [comment]
> Hi @mdable2 For text detection, only `det_polygons` and `det_scores` will be returned in Inferencer as shown below.
> 
> https://github.com/open-mmlab/mmocr/blob/bbe8964f00c93941546f19929209ff9750b2bf87/mmocr/apis/inferencers/mmocr_inferencer.py#L379-L382
> 
> If you want to get the `det_bboxes`, you can implement it with the following code.
> 
> ```python
> from mmocr.utils import poly2bbox
> det_bboxes = [poly2bbox(poly.reshape(-1)) for poly in det_polygons]from mmocr.utils import poly2bbox det_bboxes = [poly2bbox（poly.reshape（-1））for poly in det_polygons]
> ```

I meet the same question, and i tried the following code, but it recommended me with the following:
Exception has occurred: AttributeError
'list' object has no attribute 'reshape'
  File "E:\localtest\mm_lpr\mm_lpr\mmocr\demo.py", line 15, in <listcomp>
    det_bboxes = [poly2bbox(poly.reshape(-1)) for poly in det_polygons]
  File "E:\localtest\mm_lpr\mm_lpr\mmocr\demo.py", line 15, in <module>
    det_bboxes = [poly2bbox(poly.reshape(-1)) for poly in det_polygons]
AttributeError: 'list' object has no attribute 'reshape'
, in addition, i had tried to transfer the ploy to np.array but it recommended me that " setting an array element with a sequence. xxxx",can you help me? thanks a lot.
