### ISSUE TITLE
[Bug] lmdb dataset visualization error

### ISSUE THREAD

**Issue by wangjiale1998** [open-mmlab/mmocr#1973]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

System environment:
    sys.platform: win32
    Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
    CUDA available: True
    numpy_random_seed: 1207759967
    GPU 0: GeForce GTX 1080 Ti
    CUDA_HOME: None
    MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30137 版
    GCC: n/a
    PyTorch: 1.10.1
    PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_8
6;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE
_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON,
 USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

    TorchVision: 0.11.2
    OpenCV: 4.8.0
    MMEngine: 0.8.4

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 1207759967
    Distributed launcher: none
    Distributed training: False
    GPU number: 1

### Reproduces the problem - code sample

_base_ = [
    '../_base_/default_runtime.py',
    '../_base_/datasets/mjsynth.py',
    '../_base_/datasets/synthtext.py',
    '../_base_/datasets/cute80.py',
    '../_base_/datasets/iiit5k.py',
    '../_base_/datasets/svt.py',
    '../_base_/datasets/svtp.py',
    '../_base_/datasets/icdar2003.py',
    '../_base_/datasets/icdar2013_lmdb.py',
    '../_base_/datasets/icdar2015_lmdb.py',
    '../_base_/schedules/schedule_adam_base.py',
]
test_pipeline = [
    dict(type='LoadImageFromNDArray'),
    dict(type='Resize', scale=(256, 64), keep_ratio=False),
    # dict(
    #     type='RescaleToHeight',
    #     height=32,
    #     min_width=32,
    #     max_width=100,
    #     width_divisor=4),
    # dict(type='PadToWidth', width=100),
    dict(type='LoadOCRAnnotations', with_text=True),
    dict(
        type='PackTextRecogInputs',
        meta_keys=('img_path', 'ori_shape', 'img_shape', 'valid_ratio'))
]
val_dataloader = dict(
    batch_size=64,
    num_workers=0,
    persistent_workers=False,
    pin_memory=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='ConcatDataset',
        datasets=test_list,
        pipeline=test_pipeline))

vis_backends = [
    dict(type='LocalVisBackend'),
    dict(type='TensorboardVisBackend')
]
visualizer = dict(
    type='TextRecogLocalVisualizer',
    name='visualizer',
    vis_backends=vis_backends)

### Reproduces the problem - command or script

python tools/test.py [configs] [.pth] --show-dir workdirs

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/test.py", line 141, in <module>
    main()
  File "tools/test.py", line 137, in main
    runner.test()
  File "C:\Users\82307\.conda\envs\mmlab\lib\site-packages\mmengine\runner\runner.py", line 1791, in test
    metrics = self.test_loop.run()  # type: ignore
  File "C:\Users\82307\.conda\envs\mmlab\lib\site-packages\mmengine\runner\loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "C:\Users\82307\.conda\envs\mmlab\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\82307\.conda\envs\mmlab\lib\site-packages\mmengine\runner\loops.py", line 456, in run_iter
    self.runner.call_hook(
  File "C:\Users\82307\.conda\envs\mmlab\lib\site-packages\mmengine\runner\runner.py", line 1807, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "e:\code\mmocr-main\mmocr\engine\hooks\visualization_hook.py", line 118, in after_test_iter
    img_bytes = fileio.get(img_path, backend_args=self.backend_args)
  File "C:\Users\82307\.conda\envs\mmlab\lib\site-packages\mmengine\fileio\io.py", line 179, in get
    backend = get_file_backend(
  File "C:\Users\82307\.conda\envs\mmlab\lib\site-packages\mmengine\fileio\io.py", line 137, in get_file_backend
    raise ValueError(
ValueError: uri should not be None when "backend" does not exist in backend_args

### Additional information

是否lmdb文件进行测试不能显示结果图片，删去图片显示后测试正常完成了

**Comment by thangphung215** [comment]
I have this bug too
