### ISSUE TITLE
KIE training fails to reproduce WildReceipt

### ISSUE THREAD

**Issue by amitbcp** [open-mmlab/mmocr#203]
On running KIE training on the wildreceipt dataset without any changes fails. The failure/error occurs in both v.0.1.0 and latest commit. The error in v0.1.0 for custom dataset was logged in https://github.com/open-mmlab/mmocr/issues/108 but the same error occurs for wild receipt too.

Also, I am using the docker provided in the repo to build the environment and logs are from the docker. FYI Custom datasets have similar problems

Logs are attached : 
**V0.1.0** : 
```
 ./tools/dist_train.sh configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py ./work_dirs/kie 12021-05-17 11:12:51,110 - mmocr - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: Tesla V100-PCIE-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.5.2
MMCV: 1.2.6
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMOCR: 0.1.0+5244984
------------------------------------------------------------

2021-05-17 11:12:51,404 - mmocr - INFO - Distributed training: False
2021-05-17 11:12:51,780 - mmocr - INFO - Config:

** removing Dictionary Print of Config**
**original one used without any changes**

/mmocr/mmocr/apis/train.py:76: UserWarning: config is now expected to have a `runner` section, please set `runner` in your config.
  'please set `runner` in your config.', UserWarning)
2021-05-17 11:12:54,164 - mmocr - INFO - Start running, host: root@437e07e41216, work_dir: /mmocr/work_dirs/kie
2021-05-17 11:12:54,164 - mmocr - INFO - workflow: [('train', 1)], max: 60 epochs
/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
        nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
        nonzero(Tensor input, *, bool as_tuple)
2021-05-17 11:13:07,522 - mmocr - INFO - Epoch [1][50/317]      lr: 1.000e-03, eta: 1:24:26, time: 0.267, data_time: 0.236, memory: 439, loss_node: 2.0763, loss_edge: 0.0667, acc_node: 42.9543, acc_edge: 99.9996, loss: 2.1430
2021-05-17 11:13:18,789 - mmocr - INFO - Epoch [1][100/317]     lr: 1.000e-03, eta: 1:17:38, time: 0.225, data_time: 0.196, memory: 439, loss_node: 1.2926, loss_edge: 0.0002, acc_node: 56.7531, acc_edge: 100.0000, loss: 1.2928
2021-05-17 11:13:31,043 - mmocr - INFO - Epoch [1][150/317]     lr: 1.000e-03, eta: 1:17:18, time: 0.245, data_time: 0.215, memory: 477, loss_node: 0.9913, loss_edge: 0.0002, acc_node: 66.7602, acc_edge: 100.0000, loss: 0.9915
2021-05-17 11:13:42,562 - mmocr - INFO - Epoch [1][200/317]     lr: 1.000e-03, eta: 1:15:53, time: 0.230, data_time: 0.200, memory: 952, loss_node: 0.8118, loss_edge: 0.0001, acc_node: 73.4139, acc_edge: 100.0000, loss: 0.8119
2021-05-17 11:13:54,604 - mmocr - INFO - Epoch [1][250/317]     lr: 1.000e-03, eta: 1:15:37, time: 0.241, data_time: 0.212, memory: 952, loss_node: 0.7472, loss_edge: 0.0001, acc_node: 75.6485, acc_edge: 100.0000, loss: 0.7472
2021-05-17 11:14:06,068 - mmocr - INFO - Epoch [1][300/317]     lr: 1.000e-03, eta: 1:14:46, time: 0.229, data_time: 0.200, memory: 1213, loss_node: 0.6601, loss_edge: 0.0001, acc_node: 78.3963, acc_edge: 100.0000, loss: 0.6602
2021-05-17 11:14:10,011 - mmocr - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 472/472, 9.6 task/s, elapsed: 49s, ETA:     0sTraceback (most recent call last):
  File "./tools/train.py", line 205, in <module>
    main()
  File "./tools/train.py", line 201, in main
    meta=meta)
  File "/mmocr/mmocr/apis/train.py", line 149, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 143, in after_train_epoch
    key_score = self.evaluate(runner, results)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 162, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/mmocr/mmocr/datasets/kie_dataset.py", line 142, in evaluate
    assert set(kwargs).issubset(['logger'])
AssertionError
```
**Latest Commit Logs** 

```
./tools/dist_train.sh configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py ./work_dirs/kie 1Traceback (most recent call last):
  File "./tools/train.py", line 16, in <module>
    from mmocr.datasets import build_dataset
  File "/mmocr/mmocr/datasets/__init__.py", line 5, in <module>
    from .kie_dataset import KIEDataset
  File "/mmocr/mmocr/datasets/kie_dataset.py", line 12, in <module>
    from mmocr.datasets.pipelines import sort_vertex8
  File "/mmocr/mmocr/datasets/pipelines/__init__.py", line 6, in <module>
    from .ocr_seg_targets import OCRSegTargets
  File "/mmocr/mmocr/datasets/pipelines/ocr_seg_targets.py", line 7, in <module>
    from mmocr.models.builder import build_convertor
  File "/mmocr/mmocr/models/__init__.py", line 3, in <module>
    from . import common, kie, textdet, textrecog
  File "/mmocr/mmocr/models/textdet/__init__.py", line 1, in <module>
    from . import dense_heads, detectors, losses, necks, postprocess
  File "/mmocr/mmocr/models/textdet/dense_heads/__init__.py", line 1, in <module>
    from .db_head import DBHead
  File "/mmocr/mmocr/models/textdet/dense_heads/db_head.py", line 5, in <module>
    from .head_mixin import HeadMixin
  File "/mmocr/mmocr/models/textdet/dense_heads/head_mixin.py", line 4, in <module>
    from mmocr.models.textdet.postprocess import decode
  File "/mmocr/mmocr/models/textdet/postprocess/__init__.py", line 1, in <module>
    from .wrapper import decode
  File "/mmocr/mmocr/models/textdet/postprocess/wrapper.py", line 5, in <module>
    from mmcv.ops import contour_expand, pixel_group
ImportError: cannot import name 'contour_expand' from 'mmcv.ops' (/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py)
```

**Comment by innerlee** [comment]
mmcv need to be upgraded to the latest version (v1.3.4). As a part of the effort of simplifying installation, we have moved all ops from mmocr into mmcv.

mmdet also need to be in suitable version. Details see the installation page in doc.

**Comment by amitbcp** [comment]
Thanks @innerlee .
Also for v0.1.0 it works using the flag --no-validate
