### ISSUE TITLE
Request for replacing the download link of ctw1500 (test_labels.zip) with a working one

### ISSUE THREAD

**Issue by YaohouF** [open-mmlab/mmocr#2060]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmocr/issues) and [Discussions](https://github.com/open-mmlab/mmocr/discussions) but cannot get the expected help.
- [x] The bug has not been fixed in the [latest version (0.x)](https://github.com/open-mmlab/mmocr) or [latest version (1.x)](https://github.com/open-mmlab/mmocr/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmocr

### Environment

TorchVision: 0.11.3
OpenCV: 4.9.0
MMEngine: 0.10.3
MMOCR: 1.0.1+b18a09b

### Reproduces the problem - code sample

test_preparer = dict(
    obtainer=dict(
        type='NaiveDataObtainer',
        cache_path=cache_path,
        files=[
            dict(
                url='https://universityofadelaide.box.com/shared/static/'
                't4w48ofnqkdw7jyc4t11nsukoeqk9c3d.zip',
                save_name='ctw1500_test_images.zip',
                md5='79103fd77dfdd2c70ae6feb3a2fb4530',
                split=['test'],
                content=['image'],
                mapping=[[
                    'ctw1500_test_images/test_images', 'textdet_imgs/test'
                ]]),
            dict(
                url='https://cloudstor.aarnet.edu.au/plus/s/uoeFl0pCN9BOCN5/'
                'download',
                save_name='ctw1500_test_labels.zip',
                md5='7f650933a30cf1bcdbb7874e4962a52b',
                split=['test'],
                content=['annotation'],
                mapping=[['ctw1500_test_labels', 'annotations/test']])
        ]),
    gatherer=dict(
        type='PairGatherer',
        img_suffixes=['.jpg', '.JPG'],
        rule=[r'(\d{4}).jpg', r'000\1.txt']),
    parser=dict(type='CTW1500AnnParser'),
    packer=dict(type='TextDetPacker'),
    dumper=dict(type='JsonDumper'),
)

### Reproduces the problem - command or script

python tools/dataset_converters/prepare_dataset.py ctw1500 --task textdet

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/dataset_converters/prepare_dataset.py", line 153, in <module>
    main()
  File "tools/dataset_converters/prepare_dataset.py", line 149, in main
    preparer.run(args.splits)
  File "/var/autofs/home/casa/usrs/yoho/.local/text_detect_proj/mmocr/mmocr/datasets/preparers/data_preparer.py", line 85, in run
    self.loop(split, getattr(self, f'{split}_preparer'))
  File "/var/autofs/home/casa/usrs/yoho/.local/text_detect_proj/mmocr/mmocr/datasets/preparers/data_preparer.py", line 132, in loop
    obtainer()
  File "/var/autofs/home/casa/usrs/yoho/.local/text_detect_proj/mmocr/mmocr/datasets/preparers/obtainers/naive_data_obtainer.py", line 56, in __call__
    self.download(url=url, dst_path=download_path)
  File "/var/autofs/home/casa/usrs/yoho/.local/text_detect_proj/mmocr/mmocr/datasets/preparers/obtainers/naive_data_obtainer.py", line 103, in download
    request.urlretrieve(url, dst_path, progress)
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/usrs/yoho/anaconda3/envs/mmlab/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

### Additional information

Hi there, just want to see if anyone is able to share the ctw1500 dataset? When I try to prepare the ctw1500 dataset, the download link no longer works, and the other versions I found seem to have been modified. Thank you very much:)

**Comment by dengdengdenggoo** [comment]
有人ctw1500数据集吗？？

**Comment by YaohouF** [comment]
The download link of original test labels can be found at (https://universityofadelaide.box.com/shared/static/ys234cg1rtgke051hu33lbm5ri0bvxr0.zip).
