### ISSUE TITLE
Using OCR_ image_demo.py，There was an interpreter error。

### ISSUE THREAD

**Issue by gittjob** [open-mmlab/mmocr#296]
```bash
Traceback (most recent call last):
  File "/data2/enducation/OCR/mmocr-main/demo/ocr_image_demo.py", line 9, in <module>
    from mmocr.datasets.pipelines.crop import crop_img
  File "/data2/enducation/OCR/mmocr-main/mmocr/datasets/__init__.py", line 5, in <module>
    from .kie_dataset import KIEDataset
  File "/data2/enducation/OCR/mmocr-main/mmocr/datasets/kie_dataset.py", line 10, in <module>
    from mmocr.datasets.pipelines import sort_vertex8
  File "/data2/enducation/OCR/mmocr-main/mmocr/datasets/pipelines/__init__.py", line 6, in <module>
    from .ner_transforms import NerTransform, ToTensorNER
  File "/data2/enducation/OCR/mmocr-main/mmocr/datasets/pipelines/ner_transforms.py", line 4, in <module>
    from mmocr.models.builder import build_convertor
  File "/data2/enducation/OCR/mmocr-main/mmocr/models/__init__.py", line 3, in <module>
    from . import common, kie, textdet, textrecog
  File "/data2/enducation/OCR/mmocr-main/mmocr/models/textdet/__init__.py", line 1, in <module>
    from . import dense_heads, detectors, losses, necks, postprocess
  File "/data2/enducation/OCR/mmocr-main/mmocr/models/textdet/dense_heads/__init__.py", line 2, in <module>
    from .drrg_head import DRRGHead
  File "/data2/enducation/OCR/mmocr-main/mmocr/models/textdet/dense_heads/drrg_head.py", line 8, in <module>
    from mmocr.models.textdet.modules import GCN, LocalGraphs, ProposalLocalGraphs
  File "/data2/enducation/OCR/mmocr-main/mmocr/models/textdet/modules/__init__.py", line 3, in <module>
    from .proposal_local_graph import ProposalLocalGraphs
  File "/data2/enducation/OCR/mmocr-main/mmocr/models/textdet/modules/proposal_local_graph.py", line 4, in <module>
    from lanms import merge_quadrangle_n9 as la_nms  #???? install
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/lanms/__init__.py", line 2, in <module>
    from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: Python version mismatch: module was compiled for version 3.5, while the interpreter is running version 3.7.
```

**Comment by innerlee** [comment]
It is caused by the lanms-proper package. Try to run the following in a python terminal:

```python
from lanms import merge_quadrangle_n9
```

**Comment by gittjob** [comment]
ok，its  right,thankyou!

**Comment by gittjob** [comment]
Hello, input from lands import merge in the terminal_ quadrangle_ N9 has reported an error
`(/home/unaguo/anaconda3/envs/pt1.6-py3.7) hegang@ubuntu:/data2/enducation/OCR/mmocr-main$ from lanms import merge_quadrangle_n9
from: can't read /var/mail/lanms
`
