### ISSUE TITLE
Python version mismatch: module was compiled for version 3.5, while the interpreter is running version 3.7.

### ISSUE THREAD

**Issue by gittjob** [open-mmlab/mmocr#297]
Traceback (most recent call last):
  File "demo/ocr_image_demo.py", line 10, in <module>
    from mmocr.datasets.pipelines.crop import crop_img
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/datasets/__init__.py", line 5, in <module>
    from .kie_dataset import KIEDataset
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/datasets/kie_dataset.py", line 12, in <module>
    from mmocr.datasets.pipelines import sort_vertex8
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/datasets/pipelines/__init__.py", line 6, in <module>
    from .ner_transforms import NerTransform, ToTensorNER
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/datasets/pipelines/ner_transforms.py", line 4, in <module>
    from mmocr.models.builder import build_convertor
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/models/__init__.py", line 3, in <module>
    from . import common, kie, textdet, textrecog
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/models/textdet/__init__.py", line 1, in <module>
    from . import dense_heads, detectors, losses, necks, postprocess
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/models/textdet/dense_heads/__init__.py", line 2, in <module>
    from .drrg_head import DRRGHead
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/models/textdet/dense_heads/drrg_head.py", line 8, in <module>
    from mmocr.models.textdet.modules import GCN, LocalGraphs, ProposalLocalGraphs
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/models/textdet/modules/__init__.py", line 3, in <module>
    from .proposal_local_graph import ProposalLocalGraphs
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/mmocr/models/textdet/modules/proposal_local_graph.py", line 4, in <module>
    from lanms import merge_quadrangle_n9 as la_nms
  File "/home/unaguo/anaconda3/envs/pt1.6-py3.7/lib/python3.7/site-packages/lanms/__init__.py", line 2, in <module>
    from .adaptor import merge_quadrangle_n9 as nms_impl
ImportError: Python version mismatch: module was compiled for version 3.5, while the interpreter is running version 3.7.

在终端操作from lanms import merge_quadrangle_n9  也报错

(/home/unaguo/anaconda3/envs/pt1.6-py3.7) hegang@ubuntu:/data2/enducation/OCR/mmocr-main$ from lanms import merge_quadrangle_n9
from: can't read /var/mail/lanms

**Comment by innerlee** [comment]
dup https://github.com/open-mmlab/mmocr/issues/296

**Comment by innerlee** [comment]
Please make sure `from lanms import merge_quadrangle_n9` can run successfully.

**Comment by gittjob** [comment]
Installed the latest lanms package, still can't.

**Comment by innerlee** [comment]
```bash
pip uninstall lanms
pip uninstall lanms-proper
pip install lanms-proper
```

**Comment by gittjob** [comment]
It's ready to run. Thank you
