### ISSUE TITLE
Can't successfully run Perform Testing with a Pretrained KIE Model

### ISSUE THREAD

**Issue by SWHL** [open-mmlab/mmocr#305]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
- I have already installed the relative environments by the install.md
- I want to test the KIE model, and find the demo code in the [MMOCR_Tutorial.ipynb](https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb)
- When I run the test code, I met the following bug.

**Reproduction**

1. What command or script did you run?

```shell
mkdir data
wget https://download.openmmlab.com/mmocr/data/wildreceipt.tar
tar -xf wildreceipt.tar 
mv wildreceipt ./data

python tools/test.py configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py https://download.openmmlab.com/mmocr/kie/sdmgr/sdmgr_unet16_60e_wildreceipt_20210405-16a47642.pth --eval macro_f1
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
**Q**: I haven't make any modifications.
3. What dataset did you use?
**Q**: The [wildreceipt](https://download.openmmlab.com/mmocr/data/wildreceipt.tar) dataset.

**Environment**
```text
sys.platform: linux
Python: 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:15:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: Tesla P100-PCIE-12GB
CUDA_HOME: /usr/local/cuda-10.0/
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
PyTorch: 1.6.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0+cu101
OpenCV: 4.5.1
MMCV: 1.3.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMOCR: 0.2.0+
```

**Error traceback**
If applicable, paste the error traceback here.

```log
Traceback (most recent call last):
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'pretrained'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/data/SWHL/mmocr-main/mmocr/models/kie/extractors/sdmgr.py", line 40, in __init__
    pretrained)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmdet/models/detectors/single_stage.py", line 26, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: UNet: __init__() got an unexpected keyword argument 'pretrained'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 218, in <module>
    main()
  File "tools/test.py", line 177, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SDMGR: UNet: __init__() got an unexpected keyword argument 'pretrained'
```

**Bug fix**
- I tried to find the reason of the error, but I missed it. 🙏

**Comment by cuhk-hbsun** [comment]
@SWHL The error is because the `mmcv` version (1.3.7) is incompatible with `mmocr` 0.2.0. Please install `mmcv-full==1.3.4` as [install](https://mmocr.readthedocs.io/en/latest/install.html). 
We will update `mmocr` to be compatible with higher `mmcv` in the next release.

**Comment by SWHL** [comment]
Thanks

**Comment by SWHL** [comment]
When I reinstall `mmcv==1.3.4`, the error is still there.
But when I reinstall `mmdet==2.11.0` and `mmv==1.3.4`, the error is gone.
