### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpt8njhdy_/tmpg3dztyrm.py'

### ISSUE THREAD

**Issue by mobassir94** [open-mmlab/mmocr#333]
nrtr_r31_1by16_1by8_academic
nrtr_r31_1by8_1by4_academic
these 2 files worked for me in pytorch 1.8.1 later i had to update pytorch and other stuffs for training mmocr detection models on rtx 3090 gpu,
after updating environment i was able to train all the detecton models of mmocr and all the recognizer models except segocr and nrtr_r31_1by8_1by4_academic
i don't have dataset for segocr so i couldn't test it,,but nrtr_r31_1by8_1by4_academic this one is not working for me where it worked for me few days ago on torch 1.8.1 and mmcv,pycocotools and other few libraries that were different at that moment,fortunately this py file is still working for me : nrtr_r31_1by16_1by8_academic
but this one is not working nrtr_r31_1by8_1by4_academic

i get this error while running that file : 

Traceback (most recent call last):
  File "train_any_mmocr_recognizer.py", line 95, in <module>
    cfg = Config.fromfile('../configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py') 
  File "/home/apsisdev/mmcv/mmcv/utils/config.py", line 254, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/apsisdev/mmcv/mmcv/utils/config.py", line 148, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/apsisdev/anaconda3/envs/ocr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpt8njhdy_/tmpg3dztyrm.py", line 113, in <module>
NameError: name 'ttrain_ann_file11' is not defined
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fe3c55ae040>
Traceback (most recent call last):
  File "/home/apsisdev/anaconda3/envs/ocr/lib/python3.8/tempfile.py", line 441, in __del__
    self.close()
  File "/home/apsisdev/anaconda3/envs/ocr/lib/python3.8/tempfile.py", line 437, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpt8njhdy_/tmpg3dztyrm.py'

**Comment by mobassir94** [comment]
sorry,super silly mistake,,,there is no ttrain_ann_file11 in the config but train_ann_file11 that i created,,sorry for this silly mistake,,i am unable to delete this issue,,if i could i would delete this silly issue,,sorry

**Comment by innerlee** [comment]
no worries. everyone makes mistakes :)
