### ISSUE TITLE
nrtr去转onnx的时候，会遇到KeyError: 'resize_shape'这个错误

### ISSUE THREAD

**Issue by cjt222** [open-mmlab/mmocr#432]
我运行python tools/deployment/pytorch2onnx.py configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py work_dirs/latest.pth recog 00000000.jpg --output-file nrtr.onnx 的时候，会报如下错，请问是什么原因？

Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 376, in <module>
    main()
  File "tools/deployment/pytorch2onnx.py", line 372, in main
    dynamic_export=args.dynamic_export)
  File "tools/deployment/pytorch2onnx.py", line 230, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/onnx/utils.py", line 698, in _export
    dynamic_axes=dynamic_axes)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/onnx/utils.py", line 456, in _model_to_graph
    use_new_jit_passes)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/onnx/utils.py", line 417, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/onnx/utils.py", line 377, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/jit/_trace.py", line 1139, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/jit/_trace.py", line 130, in forward
    self._force_outplace,
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/kpl/.conda/envs/pvt2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/kpl/mmocr/mmocr/models/textrecog/recognizer/base.py", line 93, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/kpl/mmocr/mmocr/models/textrecog/recognizer/base.py", line 71, in forward_test
    return self.simple_test(imgs, img_metas, **kwargs)
  File "/home/kpl/mmocr/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py", line 132, in simple_test
    valid_ratio = 1.0 * img_meta['resize_shape'][1] / img.size(-1)
KeyError: 'resize_shape'

**Comment by gaotongxiao** [comment]
Sorry, we currently don't support the deployment of NRTR, and it's also not in our immediate plan either. Please check https://mmocr.readthedocs.io/en/latest/deployment.html#list-of-supported-models-exportable-to-onnx for supported models
