### ISSUE TITLE
when I run ocr_image_demo.py, it arising 'PSENet is not in the models registry" error.

### ISSUE THREAD

**Issue by QishuoLu** [open-mmlab/mmocr#457]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

Traceback (most recent call last):
  File "G:/luqs/ocr/mmocr/demo/image_demo.py", line 49, in <module>
    main()
  File "G:/luqs/ocr/mmocr/demo/image_demo.py", line 27, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "C:\Users\luqs\anaconda3\envs\mmdet_pt38_pt18\lib\site-packages\mmdet\apis\inference.py", line 39, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "C:\Users\luqs\anaconda3\envs\mmdet_pt38_pt18\lib\site-packages\mmdet\models\builder.py", line 57, in build_detector
    return DETECTORS.build(
  File "c:\users\luqs\downloads\mmcv-master\mmcv-master\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "c:\users\luqs\downloads\mmcv-master\mmcv-master\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "c:\users\luqs\downloads\mmcv-master\mmcv-master\mmcv\utils\registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'PSENet is not in the models registry'

**Reproduction**

1. What command or script did you run?

python ocr_image_demo.py 

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by gaotongxiao** [comment]
Duplicate #449
