### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

### ISSUE THREAD

**Issue by pushpalatha1405** [open-mmlab/mmocr#483]
**Notice**

There are several common situations in the reimplementation issues as below

1. Reimplement a model in the model zoo on other dataset (e.g., custom datasets)

when iam training the mmocr SDMGR model on the custom dataset, getting above error . I have created my custom dataset in the annotation form same as wildreceipt dataset  annotation form.

**Checklist**

1. I have searched related issues but cannot get the expected help.
pls help me to resolve the above type error.I will be sending the train.txt and config file which iam using.Let me know where iam making mistake, as iam not able to train SDMGR model 
[train.txt.txt](https://github.com/open-mmlab/mmocr/files/7123005/train.txt.txt)
[model.txt](https://github.com/open-mmlab/mmocr/files/7123019/model.txt)
on my custom dataset.

**Describe the issue**

A clear and concise description of what the problem you meet and what have you done.

**Reproduction**

1. What command or script did you run?

python /disk2/mmocr/tools/train.py /disk2/mmocr/configs/kie/sdmgr/sdmgr_unet16_60e_wildinvoice.py --work-dir /disk2/mmocr/sdmgr_invoice --gpu-ids 0

2. What config dir you run?

/configs/sdmgr_unet16_60e_wildinvoice.py , a bit modified script according to my custom dataset, similar to /configs/sdmgr_unet16_60e_wildreceipt.py.

3. Did you make any modifications on the code or config? Did you understand what you have modified?
yes i will be sharing the config file which i have modified to suite my custom dataset

4. What dataset did you use?
Invoice dataset

Error:
2021-09-07 14:51:07,611 - mmocr - INFO - workflow: [('train', 1)], max: 1 epochs
2021-09-07 14:51:10,040 - mmocr - INFO - Exp name: sdmgr_unet16_60e_wildinvoice.py
2021-09-07 14:51:10,040 - mmocr - INFO - Epoch [1][1/1] lr: 1.000e-03, eta: 0:00:00, time: 2.426, data_time: 2.115, memory: 677, loss_node: 2.6707, loss_edge: 0.7658, acc_node: 0.0000, acc_edge: 0.0000, loss: 3.4365
2021-09-07 14:51:10,065 - mmocr - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>                         ] 1/2, 5.3 task/s, elapsed: 0s, ETA:     0sTraceback (most recent call last):
  File "/disk2/mmocr/tools/train.py", line 221, in <module>
    main()
  File "/disk2/mmocr/tools/train.py", line 217, in main
    meta=meta)
  File "/disk2/mmocr/mmocr/apis/train.py", line 163, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 220, in after_train_epoch
    self._do_evaluate(runner)
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 17, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/test.py", line 25, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

.

**Comment by gaotongxiao** [comment]
The error occurred during the evaluation. You need to check if your test set (test.txt) has all the necessary fields filled like your train.txt.

**Comment by pushpalatha1405** [comment]
Thanks Thong i could resolve the above error and i can train my custom dataset (Pls Note as of now, i trained my custom dataset only for few epochs)

Please help me to resolve how to test/infer as iam stuck here ,Now i need to test,so i used below ways:

a)I used the available mmocr test.py script as below and saved the output in output.pkl(Is there any way to infer from this output.pkl)

python /disk2/mmocr/tools/test.py /disk2/mmocr/configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt_min_DS.py sdmgr/latest.pth --out /disk2/mmocr/output.pkl (other testing options leads to error or doesnt work)

b)I used ocr.py for inferencing as below

python mmocr/utils/ocr.py /disk2/mmocr/tests/data/invoice_DS/imgs/test/invoice1.jpg --kie-config /disk2/mmocr/configs/sdmgr_unet16_60e_wildinvoice.py --kie-ckpt /disk2/mmocr/sdmgr_invoice/epoch5.pth --device cuda:0 --output /disk2/mmocr/sdmgr_invoice

i will send u the generated output image file, there i could see only text detection and recognition(should i train on more images then is it possible to see KIE model output?)

![out_invoice1](https://user-images.githubusercontent.com/89391456/132502835-674159af-23c6-4ee0-975a-ba5f5dc96cd2.png)

c) i made modifications in the config file in the model dict section adding init_cfg key as below:

model = dict(
     type='SDMGR',
     backbone=dict(type='UNet', base_channels=16),
     bbox_head=dict(
         type='SDMGRHead', visual_dim=16, num_chars=92, num_classes=14),
      visual_modality=True,
      #init_cfg=dict(type='Pretrained', checkpoint='/disk2/mmocr/config/kie/sdmgr/sdmgr_unet16_60e_wildreceipt_20210520-7489e6de.pth'),
      init_cfg=dict(type='Pretrained', checkpoint='/disk2/mmocr/config/kie/sdmgr/epoch_5.pth'),
      train_cfg=None,
      test_cfg=None,
      class_list=f'{data_root}/class_list.txt')

BUT STILL WHEN I USE THE API mmocr.apis. init_detector(cfg, checkpoint1, device="cuda:0"), i get BELOW ERROR:

File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'pretrained'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 8, in <module>
    model = init_detector(cfg, checkpoint1, device="cuda:0")
  File "/disk2/mmocr/mmocr/apis/inference.py", line 40, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/disk2/mmocr/mmocr/models/builder.py", line 140, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/disk2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SDMGR: __init__() got an unexpected keyword argument 'pretrained'

**Comment by gaotongxiao** [comment]
I'm closing this as we have moved the discussion to #481
