### ISSUE TITLE
Slice in Data doesn't work

### ISSUE THREAD

**Issue by yCobanoglu** [open-mmlab/mmocr#501]
Passing slice to dataset doesn't work.

**Reproduction**

1. What command or script did you run?

```python3
def display_images_after_pipeline(dataset, sample_size=10) -> None:
    for index, i in enumerate(dataset[:sample_size]):  # slice in datasets doesn't work
        img = i["img"].data
        transforms.ToPILImage()(img[0]).save(f"temp/dataloader/{index}.jpg")
```

```python3
Traceback (most recent call last):
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/cuneiform_sign_detection/train_debug_cpu.py", line 91, in <module>
    display_images_after_pipeline(datasets[0])
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/cuneiform_sign_detection/utils/display_images_after_pipeline.py", line 5, in display_images_after_pipeline
    for index, i in enumerate(dataset[:sample_size]):  # slice in datasets doesn't work
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 195, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 213, in prepare_train_img
    ann_info = self.get_ann_info(idx)
  File "/home/yunus/PycharmProjects/cuneiform-sign-detection/.venv/lib/python3.9/site-packages/mmdet/datasets/coco.py", line 77, in get_ann_info
    img_id = self.data_infos[idx]['id']
TypeError: list indices must be integers or slices, not str
```

**Comment by gaotongxiao** [comment]
Our datasets implement the interface in `torch.utils.data.Dataset` which doesn't require the slicing behavior. A workaround you can use is `[dataset[i] for i in range(min(sample_size, len(dataset)))]`.
