### ISSUE TITLE
Train a SAR model with custom Google Drive datatset in GoogleColab

### ISSUE THREAD

**Issue by sisifo3** [open-mmlab/mmocr#512]
# Following the tutorial to train the SAR model, I generate the following code where my database is in Google Drive and I'm using Google Colab. 

`from mmcv import Config
cfg = Config.fromfile('./configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py')

from mmdet.apis import set_random_seed

#Set up working dir to save files and logs.
cfg.work_dir = './demo/tutorial_exps'

  #The original learning rate (LR) is set for 8-GPU training.
  #We divide it by 8 since we only use one GPU.
cfg.optimizer.lr = 0.001 / 8
cfg.lr_config.warmup = None
#Choose to log training results every 40 images to reduce the size of log file. 
cfg.log_config.interval = 40

   #Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)

cfg.total_epochs = 1

cfg.prefix = '/.content/drive/MyDrive/tecProy/'

cfg.train_ann_file ='/.content/drive/MyDrive/tecProy/label.lmdb'

cfg.img_prefix= '/.content/drive/MyDrive/tecProy/train'
cfg.train_anno_file1 ='/.content/drive/MyDrive/tecProy/label.lmdb'

cfg.train_anno_file2 = '/.content/drive/MyDrive/tecProy/label.lmdb'
cfg.test_anno_file1 = '/.content/drive/MyDrive/tecProy/label.lmdb'

cfg.test.ann_file ='/.content/drive/MyDrive/tecProy/label.txt'
cfg.test.img_prefix ='/.content/drive/MyDrive/tecProy/train'

cfg.train1.img_prefix = '/.content/drive/MyDrive/tecProy/train'
cfg.train1.ann_file = '/.content/drive/MyDrive/tecProy/label.lmdb' 

cfg.train2.img_prefix = '/.content/drive/MyDrive/tecProy/train'
cfg.train2.ann_file = '/.content/drive/MyDrive/tecProy/label.lmdb' 

cfg.data.train.datasets[0].img_prefix = "/.content/drive/MyDrive/tecProy/train"
cfg.data.train.datasets[0].ann_file = "/.content/drive/MyDrive/tecProy/label.lmdb" 

cfg.data.test.datasets[0].img_prefix = "/.content/drive/MyDrive/tecProy/train"
cfg.data.test.datasets[0].ann_file = "/.content/drive/MyDrive/tecProy/label.lmdb" 

cfg.data.train.datasets[1].img_prefix = "/.content/drive/MyDrive/tecProy/train"
cfg.data.train.datasets[1].ann_file = "/.content/drive/MyDrive/tecProy/label.lmdb" 
cfg.data.train.datasets[1].loader.ann_file = "/.content/drive/MyDrive/tecProy/label.lmdb" 

cfg.data.val.datasets[0].img_prefix = "/.content/drive/MyDrive/tecProy/train"
cfg.data.val.datasets[0].ann_file = "/.content/drive/MyDrive/tecProy/label.lmdb" 

#We can initialize the logger for training and have a look
#at the final config used for training
print(f'Config:\n{cfg.pretty_text}')

from mmocr.datasets import build_dataset
from mmocr.models import build_detector
from mmocr.apis import train_detector
import os.path as osp

#Build dataset
datasets = [build_dataset(cfg.data.train)]

#Build the detector
model = build_detector(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
#Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

#Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
`

# But I have the following problem, I would really appreciate some advice, thank you very much.

`---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

12 frames

AssertionError: /.content/drive/MyDrive/tecProy/label.lmdb is not exist

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)

AssertionError: HardDiskLoader: /.content/drive/MyDrive/tecProy/label.lmdb is not exist

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)

AssertionError: OCRDataset: HardDiskLoader: /.content/drive/MyDrive/tecProy/label.lmdb is not exist

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     53     except Exception as e:
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 
     57 

AssertionError: UniformConcatDataset: OCRDataset: HardDiskLoader: /.content/drive/MyDrive/tecProy/label.lmdb is not exist`

**Comment by sisifo3** [comment]
# Thanks again and I add config file 

`Config:
checkpoint_config = dict(interval=1)
log_config = dict(interval=40, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
label_convertor = dict(
    type='AttnConvertor', dict_type='DICT90', with_unknown=True)
model = dict(
    type='SARNet',
    backbone=dict(type='ResNet31OCR'),
    encoder=dict(
        type='SAREncoder', enc_bi_rnn=False, enc_do_rnn=0.1, enc_gru=False),
    decoder=dict(
        type='ParallelSARDecoder',
        enc_bi_rnn=False,
        dec_bi_rnn=False,
        dec_do_rnn=0,
        dec_gru=False,
        pred_dropout=0.1,
        d_k=512,
        pred_concat=True),
    loss=dict(type='SARLoss'),
    label_convertor=dict(
        type='AttnConvertor', dict_type='DICT90', with_unknown=True),
    max_seq_len=30)
optimizer = dict(type='Adam', lr=0.000125)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[3, 4], warmup=None)
total_epochs = 1
img_norm_cfg = dict(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=48,
        min_width=48,
        max_width=160,
        keep_aspect_ratio=True),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'resize_shape', 'text', 'valid_ratio'
        ])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='ResizeOCR',
        height=48,
        min_width=48,
        max_width=160,
        keep_aspect_ratio=True),
    dict(type='ToTensorOCR'),
    dict(type='NormalizeOCR', mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
    dict(
        type='Collect',
        keys=['img'],
        meta_keys=[
            'filename', 'ori_shape', 'resize_shape', 'valid_ratio',
            'img_norm_cfg', 'ori_filename'
        ])
]
dataset_type = 'OCRDataset'
img_prefix = '/.content/drive/MyDrive/tecProy/train'
train_anno_file1 = '/.content/drive/MyDrive/tecProy/label.lmdb'
train1 = dict(
    type='OCRDataset',
    img_prefix='/.content/drive/MyDrive/tecProy/train',
    ann_file='/.content/drive/MyDrive/tecProy/label.lmdb',
    loader=dict(
        type='HardDiskLoader',
        repeat=100,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)
train_anno_file2 = '/.content/drive/MyDrive/tecProy/label.lmdb'
train2 = dict(
    type='OCRDataset',
    img_prefix='/.content/drive/MyDrive/tecProy/train',
    ann_file='/.content/drive/MyDrive/tecProy/label.lmdb',
    loader=dict(
        type='LmdbLoader',
        repeat=100,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=False)
test_anno_file1 = '/.content/drive/MyDrive/tecProy/label.lmdb'
test = dict(
    type='OCRDataset',
    img_prefix='/.content/drive/MyDrive/tecProy/train',
    ann_file='/.content/drive/MyDrive/tecProy/label.txt',
    loader=dict(
        type='LmdbLoader',
        repeat=10,
        parser=dict(
            type='LineStrParser',
            keys=['filename', 'text'],
            keys_idx=[0, 1],
            separator=' ')),
    pipeline=None,
    test_mode=True)
data = dict(
    workers_per_gpu=2,
    samples_per_gpu=8,
    train=dict(
        type='UniformConcatDataset',
        datasets=[
            dict(
                type='OCRDataset',
                img_prefix='/.content/drive/MyDrive/tecProy/train',
                ann_file='/.content/drive/MyDrive/tecProy/label.lmdb',
                loader=dict(
                    type='HardDiskLoader',
                    repeat=100,
                    parser=dict(
                        type='LineStrParser',
                        keys=['filename', 'text'],
                        keys_idx=[0, 1],
                        separator=' '),
                    ann_file='/content/drive/MyDrive/tecProy/label.lmdb'),
                pipeline=[
                    dict(type='LoadImageFromFile'),
                    dict(
                        type='ResizeOCR',
                        height=48,
                        min_width=48,
                        max_width=160,
                        keep_aspect_ratio=True),
                    dict(type='ToTensorOCR'),
                    dict(
                        type='NormalizeOCR',
                        mean=[0.5, 0.5, 0.5],
                        std=[0.5, 0.5, 0.5]),
                    dict(
                        type='Collect',
                        keys=['img'],
                        meta_keys=[
                            'filename', 'ori_shape', 'resize_shape', 'text',
                            'valid_ratio'
                        ])
                ],
                test_mode=False),
            dict(
                type='OCRDataset',
                img_prefix='/.content/drive/MyDrive/tecProy/train',
                ann_file='/.content/drive/MyDrive/tecProy/label.lmdb',
                loader=dict(
                    type='LmdbLoader',
                    repeat=100,
                    parser=dict(
                        type='LineStrParser',
                        keys=['filename', 'text'],
                        keys_idx=[0, 1],
                        separator=' '),
                    ann_file='/.content/drive/MyDrive/tecProy/label.lmdb'),
                pipeline=[
                    dict(type='LoadImageFromFile'),
                    dict(
                        type='ResizeOCR',
                        height=48,
                        min_width=48,
                        max_width=160,
                        keep_aspect_ratio=True),
                    dict(type='ToTensorOCR'),
                    dict(
                        type='NormalizeOCR',
                        mean=[0.5, 0.5, 0.5],
                        std=[0.5, 0.5, 0.5]),
                    dict(
                        type='Collect',
                        keys=['img'],
                        meta_keys=[
                            'filename', 'ori_shape', 'resize_shape', 'text',
                            'valid_ratio'
                        ])
                ],
                test_mode=False)
        ],
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='ResizeOCR',
                height=48,
                min_width=48,
                max_width=160,
                keep_aspect_ratio=True),
            dict(type='ToTensorOCR'),
            dict(
                type='NormalizeOCR', mean=[0.5, 0.5, 0.5], std=[0.5, 0.5,
                                                                0.5]),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'resize_shape', 'text',
                    'valid_ratio'
                ])
        ]),
    val=dict(
        type='UniformConcatDataset',
        datasets=[
            dict(
                type='OCRDataset',
                img_prefix='/.content/drive/MyDrive/tecProy/train',
                ann_file='/.content/drive/MyDrive/tecProy/label.lmdb',
                loader=dict(
                    type='LmdbLoader',
                    repeat=10,
                    parser=dict(
                        type='LineStrParser',
                        keys=['filename', 'text'],
                        keys_idx=[0, 1],
                        separator=' ')),
                pipeline=None,
                test_mode=True)
        ],
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='ResizeOCR',
                height=48,
                min_width=48,
                max_width=160,
                keep_aspect_ratio=True),
            dict(type='ToTensorOCR'),
            dict(
                type='NormalizeOCR', mean=[0.5, 0.5, 0.5], std=[0.5, 0.5,
                                                                0.5]),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'resize_shape', 'valid_ratio',
                    'img_norm_cfg', 'ori_filename'
                ])
        ]),
    test=dict(
        type='UniformConcatDataset',
        datasets=[
            dict(
                type='OCRDataset',
                img_prefix='/.content/drive/MyDrive/tecProy/train',
                ann_file='/.content/drive/MyDrive/tecProy/label.lmdb',
                loader=dict(
                    type='LmdbLoader',
                    repeat=10,
                    parser=dict(
                        type='LineStrParser',
                        keys=['filename', 'text'],
                        keys_idx=[0, 1],
                        separator=' ')),
                pipeline=None,
                test_mode=True)
        ],
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='ResizeOCR',
                height=48,
                min_width=48,
                max_width=160,
                keep_aspect_ratio=True),
            dict(type='ToTensorOCR'),
            dict(
                type='NormalizeOCR', mean=[0.5, 0.5, 0.5], std=[0.5, 0.5,
                                                                0.5]),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=[
                    'filename', 'ori_shape', 'resize_shape', 'valid_ratio',
                    'img_norm_cfg', 'ori_filename'
                ])
        ]))
evaluation = dict(interval=1, metric='acc')
work_dir = './demo/tutorial_exps'
seed = 0
gpu_ids = range(0, 1)
prefix = '/.content/drive/MyDrive/tecProy/'
train_ann_file = '/.content/drive/MyDrive/tecProy/label.lmdb'
`

**Comment by sisifo3** [comment]
# I think I solved the first problem, it was only to specify the data format depending on 'LmdbLoader' and 'HardDiskLoader' the code was as follows: 

`from mmdet.apis import set_random_seed

# Set up working dir to save files and logs.
cfg.work_dir = './demo/tutorial_exps'

# The original learning rate (LR) is set for 8-GPU training.
# We divide it by 8 since we only use one GPU.
cfg.optimizer.lr = 0.001 / 8
cfg.lr_config.warmup = None
# Choose to log training results every 40 images to reduce the size of log file. 
cfg.log_config.interval = 40

# Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)



cfg.total_epochs = 1

cfg.prefix = '/content/drive/MyDrive/tecProy/'

#cfg.train_ann_file.img_prefix='/content/drive/MyDrive/test_img_hor/train'
cfg.train_ann_file ='/content/drive/MyDrive/tecProy/label.txt'

cfg.img_prefix= '/content/drive/MyDrive/tecProy/train'
cfg.train_anno_file1 ='/content/drive/MyDrive/tecProy/label.txt'

cfg.train_anno_file2 = '/content/drive/MyDrive/tecProy/label.lmdb'
cfg.test_anno_file1 = '/content/drive/MyDrive/tecProy/label.lmdb'

cfg.test.ann_file ='/content/drive/MyDrive/tecProy/label.lmdb'
cfg.test.img_prefix ='/content/drive/MyDrive/tecProy/train'

cfg.train1.img_prefix = '/content/drive/MyDrive/tecProy/train'
cfg.train1.ann_file = '/content/drive/MyDrive/tecProy/label.txt' 

cfg.train2.img_prefix = '/content/drive/MyDrive/tecProy/train'
cfg.train2.ann_file = '/content/drive/MyDrive/tecProy/label.lmdb' 



cfg.data.train.datasets[0].img_prefix = "/content/drive/MyDrive/tecProy/train"
cfg.data.train.datasets[0].ann_file = "/content/drive/MyDrive/tecProy/label.txt" 

cfg.data.test.datasets[0].img_prefix = "/content/drive/MyDrive/tecProy/train"
cfg.data.test.datasets[0].ann_file = "/content/drive/MyDrive/tecProy/label.lmdb" 

cfg.data.train.datasets[1].img_prefix = "/content/drive/MyDrive/tecProy/train"
cfg.data.train.datasets[1].ann_file = "/content/drive/MyDrive/tecProy/label.lmdb" 
cfg.data.train.datasets[1].loader.ann_file = "/content/drive/MyDrive/tecProy/label.lmdb" 


cfg.data.val.datasets[0].img_prefix = "/content/drive/MyDrive/tecProy/train"
cfg.data.val.datasets[0].ann_file = "/content/drive/MyDrive/tecProy/label.lmdb" 


# We can initialize the logger for training and have a look
# at the final config used for training
print(f'Config:\n{cfg.pretty_text}')
`

**Comment by sisifo3** [comment]
# This leads us to the second error, when we start to train the model it shows us the following error. 

`2021-09-29 18:15:49,750 - mmocr - INFO - workflow: [('train', 1)], max: 1 epochs

prepare index 695 with error key index: 1 out of range: ['']
load index 695 with error key index: 1 out of range: ['']
prepare index 983 with error key index: 1 out of range: ['']
load index 983 with error key index: 1 out of range: ['']
prepare index 587 with error key index: 1 out of range: ['']
load index 587 with error key index: 1 out of range: ['']
prepare index 863 with error key index: 1 out of range: ['']
prepare index 346 with error key index: 1 out of range: ['']
load index 863 with error key index: 1 out of range: ['']
load index 346 with error key index: 1 out of range: ['']
....
..
.
`

**Comment by sisifo3** [comment]
> # This leads us to the second error, when we start to train the model it shows us the following error.
> 
> `2021-09-29 18:15:49,750 - mmocr - INFO - workflow: [('train', 1)], max: 1 epochs
> 
> prepare index 695 with error key index: 1 out of range: [''] load index 695 with error key index: 1 out of range: [''] prepare index 983 with error key index: 1 out of range: [''] load index 983 with error key index: 1 out of range: [''] prepare index 587 with error key index: 1 out of range: [''] load index 587 with error key index: 1 out of range: [''] prepare index 863 with error key index: 1 out of range: [''] prepare index 346 with error key index: 1 out of range: [''] load index 863 with error key index: 1 out of range: [''] load index 346 with error key index: 1 out of range: [''] .... .. . `
> 
> `2021-09-29 18:25:45,095 - mmocr - INFO - Saving checkpoint at 1 epochs
> 
> [>> ] 8/120, 5.8 task/s, elapsed: 1s, ETA: 19s
> 
> Exception Traceback (most recent call last)
> 
> in () 15 # Create work_dir 16 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir)) ---> 17 train_detector(model, datasets, cfg, distributed=False, validate=True)
> 
> 10 frames
> 
> /usr/local/lib/python3.7/dist-packages/torch/_utils.py in reraise(self) 426 # have message field 427 raise self.exc_type(message=msg) --> 428 raise self.exc_type(msg) 429 430
> 
> Exception: Caught Exception in DataLoader worker process 1. Original Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop data = fetcher.fetch(index) File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py", line 218, in **getitem** return self.datasets[dataset_idx][sample_idx] File "/mmocr/mmocr/datasets/base_dataset.py", line 139, in **getitem** return self.prepare_test_img(index) File "/mmocr/mmocr/datasets/base_dataset.py", line 111, in prepare_test_img return self.prepare_train_img(img_info) File "/mmocr/mmocr/datasets/base_dataset.py", line 96, in prepare_train_img img_info = self.data_infos[index] File "/mmocr/mmocr/datasets/utils/loader.py", line 40, in **getitem** return self.parser.get_item(self.ori_data_infos, index) File "/mmocr/mmocr/datasets/utils/parser.py", line 41, in get_item f'key index: {max(self.keys_idx)} out of range: {line_str}') Exception: key index: 1 out of range: [''] `

This problem was solved, changing the photos from .png to .jpg format and that was the solution and made it possible to start the training, greetings
