### ISSUE TITLE
drrg : convert to onnx error

### ISSUE THREAD

**Issue by gjm441** [open-mmlab/mmocr#529]
when i try to convert pretrained drrg pt to onnx , i meet the problem:
python scripts:

`python` tools/deployment/pytorch2onnx.py ./configs/textdet/drrg/drrg_r50_fpn_unet_1200e_ctw1500.py ./pretrained/drrg_r50_fpn_unet_1200e_ctw1500-1abf4f67.pth 'det' ./demo/demo_densetext_det.jpg --output-file `drrg_r50_fpn_unet_1200e_ctw1500_op13.onnx` 

env:(use docker)
torch:1.9.0
torchtext:0.10.0
torchvision:0.10.0

opt/conda/lib/python3.7/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 377, in <module>
    main()
  File "tools/deployment/pytorch2onnx.py", line 373, in main
    dynamic_export=args.dynamic_export)
  File "tools/deployment/pytorch2onnx.py", line 231, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 459, in _model_to_graph
    _retain_param_name)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
RuntimeError: output 1 (35.8594
[ CPUDoubleType{} ]) of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.

can you give any suggestions? Single OCR image detection using drrg is correct.

**Comment by gjm441** [comment]
@gaotongxiao OK，thanks for reply
