### ISSUE TITLE
Error is testing Db_r50

### ISSUE THREAD

**Issue by iaditij** [open-mmlab/mmocr#571]
was trying testing using this command and getting the error... dbn.path is not a checkpoint file. Please suggest where I am wrong

!python /content/drive/MyDrive/mmocr-main/mmocr/utils/ocr.py '/content/10.jpg'  --det 'DB_r50' --det-config '/content/drive/MyDrive/mmocr-main/configs/textdet/dbnet/dbnet_r50dcnv2_fpnc_1200e_icdar2015.py' --det-ckpt '/content/drive/MyDrive/mmocr-main/configs/dbnet/dbn.pth'  --recog 'SEG' --recog-config '/content/drive/MyDrive/mmocr-main/configs/textrecog/seg/seg_r31_1by16_fpnocr_academic.py' --recog-ckpt '/content/drive/MyDrive/mmocr-main/configs/seg/seg_r31_1by16_fpnocr_academic-72235b11.pth' --kie 'SDMGR' --kie-config '/content/drive/MyDrive/mmocr-main/configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py'  --kie-ckpt '/content/latest.pth' --output './'  --print-result --imshow

error: 
/content/mmocr/mmocr/utils/ocr.py:159: UserWarning: config_dir will be overridden by det-config or recog-config.
  UserWarning)
Use load_from_local loader
Traceback (most recent call last):
  File "/content/mmocr/mmocr/utils/ocr.py", line 699, in <module>
    main()
  File "/content/mmocr/mmocr/utils/ocr.py", line 694, in main
    ocr = MMOCR(**vars(args))
  File "/content/mmocr/mmocr/utils/ocr.py", line 348, in __init__
    det_config, det_ckpt, device=self.device)
  File "/content/mmocr/mmocr/apis/inference.py", line 43, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 527, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 466, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 260, in load_from_local
    raise IOError(f'{filename} is not a checkpoint file')
/content/drive/MyDrive/mmocr-main/configs/dbnet/dbn.pth is not a checkpoint file

**Comment by gaotongxiao** [comment]
What's your PyTorch version? It might be a compatibility issue, and upgrading it should be the quickest fix.

**Comment by cuhk-hbsun** [comment]
Where do you get the `dbn.pth`? Please download the checkpoint from [official url](https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_r50dcnv2_fpnc_sbn_1200e_icdar2015_20210325-91cef9af.pth)

**Comment by iaditij** [comment]
thanks @cuhk-hbsun it worked!
