### ISSUE TITLE
Error when train model MaskRCNN_IC15 ?

### ISSUE THREAD

**Issue by ThorPham** [open-mmlab/mmocr#584]
After some iteration a bug appear : TypeError: __init__() missing 1 required positional argument: 'dtype'
Please help me fix it .

> c: 93.0518, loss_bbox: 0.2080, loss_mask: 0.2831, loss: 0.7607
2021-11-12 22:03:53,519 - mmocr - INFO - Epoch [1][85/251]	lr: 1.351e-02, eta: 12:50:11, time: 2.741, data_time: 1.014, memory: 7479, loss_rpn_cls: 0.0649, loss_rpn_bbox: 0.0446, loss_cls: 0.2799, acc: 89.5361, loss_bbox: 0.2738, loss_mask: 0.2812, loss: 0.9444
2021-11-12 22:03:59,559 - mmocr - INFO - Epoch [1][90/251]	lr: 1.431e-02, eta: 12:35:13, time: 1.208, data_time: 0.079, memory: 7479, loss_rpn_cls: 0.0464, loss_rpn_bbox: 0.0279, loss_cls: 0.2014, acc: 92.7295, loss_bbox: 0.2071, loss_mask: 0.2438, loss: 0.7266
2021-11-12 22:04:16,403 - mmocr - INFO - Epoch [1][95/251]	lr: 1.510e-02, eta: 13:09:13, time: 3.368, data_time: 2.278, memory: 7479, loss_rpn_cls: 0.0732, loss_rpn_bbox: 0.0300, loss_cls: 0.2441, acc: 91.0156, loss_bbox: 0.2370, loss_mask: 0.2547, loss: 0.8391
Traceback (most recent call last):
  File "tools/train.py", line 221, in <module>
    main()
  File "tools/train.py", line 217, in main
    meta=meta)
  File "/home/thorpham/Documents/challenge/mmocr/mmocr/apis/train.py", line 163, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'dtype'

**Comment by ThorPham** [comment]
Same data but when i train MaskRCNN_IC157 . Error like this 

> : 90.7520, loss_bbox: 0.2705, loss_mask: 0.2593, loss: 0.8591
2021-11-12 22:20:11,561 - mmocr - INFO - Epoch [1][140/214]	lr: 2.230e-02, eta: 9:12:33, time: 1.895, data_time: 0.101, memory: 7561, loss_rpn_cls: 0.0623, loss_rpn_bbox: 0.0397, loss_cls: 0.2723, acc: 89.5508, loss_bbox: 0.2915, loss_mask: 0.2431, loss: 0.9089
2021-11-12 22:20:24,311 - mmocr - INFO - Epoch [1][145/214]	lr: 2.310e-02, eta: 9:24:29, time: 2.547, data_time: 0.846, memory: 7561, loss_rpn_cls: 0.1025, loss_rpn_bbox: 0.0422, loss_cls: 0.2735, acc: 90.6006, loss_bbox: 0.2591, loss_mask: 0.2842, loss: 0.9615
2021-11-12 22:20:31,101 - mmocr - INFO - Epoch [1][150/214]	lr: 2.390e-02, eta: 9:21:36, time: 1.360, data_time: 0.045, memory: 7561, loss_rpn_cls: 0.0539, loss_rpn_bbox: 0.0345, loss_cls: 0.2708, acc: 89.7900, loss_bbox: 0.2763, loss_mask: 0.2723, loss: 0.9080
Traceback (most recent call last):
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/queues.py", line 108, in get
    res = self._recv_bytes()
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 411, in _recv_bytes
    return self._recv(size)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 386, in _recv
    buf.write(chunk)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 15034) is killed by signal: Killed. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 221, in <module>
    main()
  File "tools/train.py", line 217, in main
    meta=meta)
  File "/home/thorpham/Documents/challenge/mmocr/mmocr/apis/train.py", line 163, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 15034) exited unexpectedly

**Comment by gaotongxiao** [comment]
It seems some part of your data is wrong, you may need to check if there is any missing field or other “misbehaved” data in your training set. The epoch number right before the error occurred is certainly a hint.

**Comment by ThorPham** [comment]
@gaotongxiao  I train same data with model DBnet but no error . Do you think error belong num_workers (default num_workers=4) . I set num_workers = 0 no error but train very slow.

**Comment by ThorPham** [comment]
@gaotongxiao 
I don't know error come from. I try debug and train many times . 
Do you have any suggestions for me?  I try train many model text detection in same data. but only MaskRCNN has bug.
My log when i train success 1 epoch and eval . But epoch 2 error appear again.

> : 91.9824, loss_bbox: 0.2363, loss_mask: 0.2382, loss: 0.8149
2021-11-14 16:00:19,535 - mmocr - INFO - Epoch [1][195/214]	lr: 3.109e-02, eta: 8:39:48, time: 1.210, data_time: 0.052, memory: 7568, loss_rpn_cls: 0.0549, loss_rpn_bbox: 0.0243, loss_cls: 0.2046, acc: 92.8955, loss_bbox: 0.2211, loss_mask: 0.2626, loss: 0.7676
2021-11-14 16:00:26,568 - mmocr - INFO - Epoch [1][200/214]	lr: 3.189e-02, eta: 8:39:07, time: 1.407, data_time: 0.099, memory: 7568, loss_rpn_cls: 0.0409, loss_rpn_bbox: 0.0231, loss_cls: 0.1764, acc: 94.1797, loss_bbox: 0.1777, loss_mask: 0.2498, loss: 0.6679
2021-11-14 16:00:32,899 - mmocr - INFO - Epoch [1][205/214]	lr: 3.269e-02, eta: 8:37:15, time: 1.267, data_time: 0.094, memory: 7568, loss_rpn_cls: 0.0608, loss_rpn_bbox: 0.0364, loss_cls: 0.2776, acc: 89.7070, loss_bbox: 0.2876, loss_mask: 0.2442, loss: 0.9066
2021-11-14 16:00:38,733 - mmocr - INFO - Epoch [1][210/214]	lr: 3.349e-02, eta: 8:34:37, time: 1.165, data_time: 0.095, memory: 7568, loss_rpn_cls: 0.0370, loss_rpn_bbox: 0.0237, loss_cls: 0.2213, acc: 91.6846, loss_bbox: 0.2467, loss_mask: **0.2379, loss: 0.7666
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 300/300, 1.8 task/s, elapsed: 162s, ETA:     0s2021-11-14 16:03:25,626 - mmocr - INFO - Evaluating hmean-iou...
2021-11-14 16:03:52,956 - mmocr - INFO - thr 0.3, recall：0.556, precision: 0.811, hmean:0.660
2021-11-14 16:04:17,313 - mmocr - INFO - thr 0.4, recall：0.527, precision: 0.868, hmean:0.656
2021-11-14 16:04:38,961 - mmocr - INFO - thr 0.5, recall：0.496, precision: 0.899, hmean:0.640
2021-11-14 16:04:58,121 - mmocr - INFO - thr 0.6, recall：0.462, precision: 0.925, hmean:0.616
2021-11-14 16:05:14,509 - mmocr - INFO - thr 0.7, recall：0.407, precision: 0.942, hmean:0.568
2021-11-14 16:05:26,486 - mmocr - INFO - thr 0.8, recall：0.306, precision: 0.958, hmean:0.464
2021-11-14 16:05:30,451 - mmocr - INFO - thr 0.9, recall：0.106, precision: 0.983, hmean:0.192**
2021-11-14 16:05:30,473 - mmocr - INFO - Exp name: mask_rcnn_r50_fpn_160e_icdar2017.py
2021-11-14 16:05:30,474 - mmocr - INFO - Epoch(val) [1][300]	hmean-iou:recall: 0.5559, hmean-iou:precision: 0.8106, hmean-iou:hmean: 0.6595
2021-11-14 16:05:46,456 - mmocr - INFO - Epoch [2][5/214]	lr: 3.493e-02, eta: 8:38:49, time: 3.172, data_time: 1.635, memory: 7568, loss_rpn_cls: 0.0587, loss_rpn_bbox: 0.0436, loss_cls: 0.2678, acc: 89.6729, loss_bbox: 0.2893, loss_mask: 0.2544, loss: 0.9138
2021-11-14 16:05:52,108 - mmocr - INFO - Epoch [2][10/214]	lr: 3.572e-02, eta: 8:36:01, time: 1.130, data_time: 0.065, memory: 7568, loss_rpn_cls: 0.0442, loss_rpn_bbox: 0.0265, loss_cls: 0.1951, acc: 93.1592, loss_bbox: 0.1932, loss_mask: 0.2289, loss: 0.6878
2021-11-14 16:06:00,260 - mmocr - INFO - Epoch [2][15/214]	lr: 3.652e-02, eta: 8:37:12, time: 1.631, data_time: 0.537, memory: 7568, loss_rpn_cls: 0.0720, loss_rpn_bbox: 0.0359, loss_cls: 0.2529, acc: 91.4697, loss_bbox: 0.2567, loss_mask: 0.2945, loss: 0.9120
2021-11-14 16:06:06,008 - mmocr - INFO - Epoch [2][20/214]	lr: 3.732e-02, eta: 8:34:42, time: 1.150, data_time: 0.032, memory: 7568, loss_rpn_cls: 0.0379, loss_rpn_bbox: 0.0248, loss_cls: 0.2146, acc: 91.8359, loss_bbox: 0.2183, loss_mask: 0.2555, loss: 0.7511
2021-11-14 16:06:12,221 - mmocr - INFO - Epoch [2][25/214]	lr: 3.812e-02, eta: 8:32:58, time: 1.242, data_time: 0.076, memory: 7568, loss_rpn_cls: 0.0615, loss_rpn_bbox: 0.0308, loss_cls: 0.2011, acc: 92.8027, loss_bbox: 0.2205, loss_mask: 0.2635, loss: 0.7774
2021-11-14 16:06:18,374 - mmocr - INFO - Epoch [2][30/214]	lr: 3.892e-02, eta: 8:31:14, time: 1.230, data_time: 0.066, memory: 7568, loss_rpn_cls: 0.0333, loss_rpn_bbox: 0.0212, loss_cls: 0.2286, acc: 91.1230, loss_bbox: 0.2538, loss_mask: 0.2408, loss: 0.7777
2021-11-14 16:06:26,568 - mmocr - INFO - Epoch [2][35/214]	lr: 3.972e-02, eta: 8:32:27, time: 1.640, data_time: 0.213, memory: 7568, loss_rpn_cls: 0.0643, loss_rpn_bbox: 0.0407, loss_cls: 0.2606, acc: 90.4736, loss_bbox: 0.2753, loss_mask: 0.2900, loss: 0.9309
2021-11-14 16:06:34,685 - mmocr - INFO - Epoch [2][40/214]	lr: 4.052e-02, eta: 8:33:31, time: 1.624, data_time: 0.034, memory: 7568, loss_rpn_cls: 0.0550, loss_rpn_bbox: 0.0404, loss_cls: 0.2657, acc: 89.6094, loss_bbox: 0.2810, loss_mask: 0.2472, loss: 0.8893
2021-11-14 16:06:42,003 - mmocr - INFO - Epoch [2][45/214]	lr: 4.132e-02, eta: 8:33:26, time: 1.463, data_time: 0.392, memory: 7568, loss_rpn_cls: 0.0367, loss_rpn_bbox: 0.0252, loss_cls: 0.2267, acc: 91.8701, loss_bbox: 0.2381, loss_mask: 0.2563, loss: 0.7829
2021-11-14 16:06:50,199 - mmocr - INFO - Epoch [2][50/214]	lr: 4.212e-02, eta: 8:34:31, time: 1.639, data_time: 0.047, memory: 7568, loss_rpn_cls: 0.0468, loss_rpn_bbox: 0.0294, loss_cls: 0.2255, acc: 91.6064, loss_bbox: 0.2316, loss_mask: 0.2542, loss: 0.7875
2021-11-14 16:06:59,303 - mmocr - INFO - Epoch [2][55/214]	lr: 4.292e-02, eta: 8:36:46, time: 1.820, data_time: 0.069, memory: 7568, loss_rpn_cls: 0.1668, loss_rpn_bbox: 0.0419, loss_cls: 0.2380, acc: 91.8945, loss_bbox: 0.2202, loss_mask: 0.2615, loss: 0.9283
2021-11-14 16:07:05,370 - mmocr - INFO - Epoch [2][60/214]	lr: 4.372e-02, eta: 8:35:00, time: 1.213, data_time: 0.091, memory: 7568, loss_rpn_cls: 0.0832, loss_rpn_bbox: 0.0362, loss_cls: 0.2219, acc: 91.5771, loss_bbox: 0.2329, loss_mask: 0.2363, loss: 0.8106
Traceback (most recent call last):
  File "tools/train.py", line 221, in <module>
    main()
  File "tools/train.py", line 217, in main
    meta=meta)
  File "/home/thorpham/Documents/challenge/mmocr/mmocr/apis/train.py", line 163, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    **data.reraise()
  File "/home/thorpham/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'dtype'**
