### ISSUE TITLE
KeyError: 'img_info' when using novisual closed set kie model to infer

### ISSUE THREAD

**Issue by VignetteApril** [open-mmlab/mmocr#599]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
The following problems are encountered when using the novisual closed set kie model to infer
```none
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mmocr/mmocr/utils/ocr.py", line 705, in <module>
    main()
  File "/mmocr/mmocr/utils/ocr.py", line 701, in main
    ocr.readtext(**vars(args))
  File "/mmocr/mmocr/utils/ocr.py", line 426, in readtext
    self.detect_model, self.recog_model, kie_model=self.kie_model)
  File "/mmocr/mmocr/utils/ocr.py", line 601, in det_recog_kie_inference
    batch_mode=self.args.batch_mode)
  File "/mmocr/mmocr/apis/inference.py", line 144, in model_inference
    data = test_pipeline(data)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/mmocr/mmocr/datasets/pipelines/kie_transforms.py", line 21, in __call__
    w, h = results['img_info']['width'], results['img_info']['height']
KeyError: 'img_info'
````

**Reproduction**

1. Modify https://github.com/open-mmlab/mmocr/blob/284b5acc12f8889d44b9abc26a688dd7abeff246/mmocr/utils/ocr.py#L315
to `'config': 'sdmgr/sdmgr_novisual_60e_wildreceipt.py'`
2. Modify https://github.com/open-mmlab/mmocr/blob/284b5acc12f8889d44b9abc26a688dd7abeff246/mmocr/utils/ocr.py#L317
to `'sdmgr/sdmgr_novisual_60e_wildreceipt_20210517-a44850da.pth'`
3. Then run 
```shell
python -m mmocr.utils.ocr --config-dir `python -c 'import mmocr;print(mmocr.__path__[0])'`/../configs demo/demo_kie.jpeg --det PS_CTW --recog SAR --kie SDMGR --print-result --output . 
```

**Environment**

```none
sys.platform: linux
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) [GCC 7.3.0]
CUDA available: True
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.5.3
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMOCR: 0.3.0+284b5ac
```

**Error traceback**
```none
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mmocr/mmocr/utils/ocr.py", line 705, in <module>
    main()
  File "/mmocr/mmocr/utils/ocr.py", line 701, in main
    ocr.readtext(**vars(args))
  File "/mmocr/mmocr/utils/ocr.py", line 426, in readtext
    self.detect_model, self.recog_model, kie_model=self.kie_model)
  File "/mmocr/mmocr/utils/ocr.py", line 601, in det_recog_kie_inference
    batch_mode=self.args.batch_mode)
  File "/mmocr/mmocr/apis/inference.py", line 144, in model_inference
    data = test_pipeline(data)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/mmocr/mmocr/datasets/pipelines/kie_transforms.py", line 21, in __call__
    w, h = results['img_info']['width'], results['img_info']['height']
KeyError: 'img_info'
```

**Comment by gaotongxiao** [comment]
All you need to do is to set `ann_info['img_info']['width']` and `ann_info['img_info']['height']` as list of widths and heights right after 
https://github.com/open-mmlab/mmocr/blob/c39f1160ac1e6ecef8c42a57a95d95730a31f660/mmocr/utils/ocr.py#L595.

But you may need to figure out how to extract them from contextual variables.

**Comment by innerlee** [comment]
It is a bug in inference code https://github.com/open-mmlab/mmocr/blob/main/mmocr/apis/inference.py#L144.
There are some preparation code for a normal inference https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/base_dataset.py#L139.
This call to `prepare_test_img` will in turn call https://github.com/open-mmlab/mmocr/blob/main/mmocr/datasets/kie_dataset.py#L134-L135, where the info was appended.

**Comment by VignetteApril** [comment]
@innerlee @gaotongxiao Thanks Reply

**Comment by innerlee** [comment]
A quick fix

```diff
diff --git a/mmocr/apis/inference.py b/mmocr/apis/inference.py
index 2cd9c65..6911f23 100644
--- a/mmocr/apis/inference.py
+++ b/mmocr/apis/inference.py
@@ -129,7 +129,11 @@ def model_inference(model,
         # prepare data
         if is_ndarray:
             # directly add img
-            data = dict(img=img, ann_info=ann, bbox_fields=[])
+            data = dict(
+                img=img,
+                ann_info=ann,
+                img_info=dict(width=img.shape[1], height=img.shape[0]),
+                bbox_fields=[])
         else:
             # add information into dict
             data = dict(
```
