### ISSUE TITLE
Is SATRN exported to onnx?  If not, can Encoder and Decoder modules be exported respectively? 

### ISSUE THREAD

**Issue by yanglinxiabuaaa** [open-mmlab/mmocr#627]
Who has done this? Thank you

**Comment by gaotongxiao** [comment]
Our community member was able to export it with onnx op 14 (https://mmocr.readthedocs.io/en/latest/deployment.html#c-inference-example-with-opencv)

**Comment by yanglinxiabuaaa** [comment]
> Our community member was able to export it with onnx op 14 (https://mmocr.readthedocs.io/en/latest/deployment.html#c-inference-example-with-opencv)

Great job! Thank you for reminding me.  It's actually in the ./docs/deployment.md  about SATRN export to onnx, I tried and got an error as follows with torch1.7.0 and onnx1.9.0 :

python ./tools/deployment/pytorch2onnx.py --opset 14 --verify --output-file recognizer.onnx ./configs/textrecog/satrn/satrn_small.py ./models/satrn_small.pth recog ./tests/data/test_img1.jpg
Use load_from_local loader
Traceback (most recent call last):
  File "./tools/deployment/pytorch2onnx.py", line 349, in <module>
    main()
  File "./tools/deployment/pytorch2onnx.py", line 345, in main
    dynamic_export=args.dynamic_export)
  File "./tools/deployment/pytorch2onnx.py", line 202, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/usr/local/anaconda3/envs/ylx1/lib/python3.6/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/anaconda3/envs/ylx1/lib/python3.6/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/anaconda3/envs/ylx1/lib/python3.6/site-packages/torch/onnx/utils.py", line 616, in _export
    _set_opset_version(opset_version)
  File "/usr/local/anaconda3/envs/ylx1/lib/python3.6/site-packages/torch/onnx/symbolic_helper.py", line 508, in _set_opset_version
    raise ValueError("Unsupported ONNX opset version: " + str(opset_version))
ValueError: Unsupported ONNX opset version: 14

**Comment by gaotongxiao** [comment]
I remember that PyTorch does not support opset 14 until 1.9.0. You can upgrade your PyTorch and make another try.

**Comment by menmory3** [comment]
exported SATRN to onnx,but the size is too big ,622MB
