### ISSUE TITLE
AssertionError in tools/data/textdet/totaltext_converter.py

### ISSUE THREAD

**Issue by Xushibo96** [open-mmlab/mmocr#659]
I have trouble when running totaltext_converter.py
```
python tools/data/textdet/totaltext_converter.py data/totaltext -o data/totaltext --split-list training test
Converting training into instances_training.json
Loaded 1255 images from data/totaltext/imgs/training
[>>>>>>>>>>>>>>>>>>>         ] 894/1255, 42.8 task/s, elapsed: 21s, ETA:     8sIt takes 20.903159141540527s to convert totaltext annotation
Traceback (most recent call last):
  File "tools/data/textdet/totaltext_converter.py", line 412, in <module>
    main()
  File "tools/data/textdet/totaltext_converter.py", line 407, in main
    image_infos = collect_annotations(files, 1)
  File "tools/data/textdet/totaltext_converter.py", line 69, in collect_annotations
    images = mmcv.track_progress(load_img_info, files)
  File "/home/lhb/anaconda3/envs/pytrackingLay/lib/python3.8/site-packages/mmcv/utils/progressbar.py", line 92, in track_progress
    results.append(func(task, **kwargs))
  File "tools/data/textdet/totaltext_converter.py", line 350, in load_img_info
    assert img.shape[0:2] == img_color.shape[0:2]
AssertionError
```
I searched in issues as much as possible but did not find a solution. So i come to ask for help. Thanks a lot.

**Comment by gaotongxiao** [comment]
This assertion is no longer required and I just post a fix. If you're interested in why this assertion would fail, you can read #375 and https://mmocr.readthedocs.io/en/latest/datasets/det.html#important-note

**Comment by Xushibo96** [comment]
Got it, thank you very much.
