### ISSUE TITLE
IndexError: Caught IndexError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Y-M-Y** [open-mmlab/mmocr#671]
Thanks a lot for providing MMOCR, it's awesome and really useful!

I am using my customed coco-like dataset to train PSENet and encountered this error. This kind of coco-like dataset works well in mmdetetcion. 

Here's the config
```
checkpoint_config = dict(interval=10)
log_config = dict(interval=5, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
optimizer = dict(type='Adam', lr=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[200, 400])
total_epochs = 600
model = dict(
    type='PSENet',
    backbone=dict(
        type='mmdet.ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
        norm_eval=True,
        style='caffe'),
    neck=dict(
        type='FPNF',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        fusion_type='concat'),
    bbox_head=dict(
        type='PSEHead',
        text_repr_type='quad',
        in_channels=[256],
        out_channels=7,
        loss=dict(type='PSELoss')),
    train_cfg=None,
    test_cfg=None)
dataset_type = 'IcdarDataset'
data_root = 'data/icdar2015/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
    dict(
        type='LoadTextAnnotations',
        with_bbox=True,
        with_mask=True,
        poly2mask=False),
    dict(type='ColorJitter', brightness=0.12549019607843137, saturation=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(
        type='ScaleAspectJitter',
        img_scale=[(1200, 800)],
        ratio_range=(0.5, 3),
        aspect_ratio_range=(1, 1),
        multiscale_mode='value',
        long_size_bound=1280,
        short_size_bound=640,
        resize_type='long_short_bound',
        keep_ratio=False),
    dict(type='PSENetTargets'),
    dict(type='RandomFlip', flip_ratio=0.5, direction='horizontal'),
    dict(type='RandomRotateTextDet'),
    dict(
        type='RandomCropInstances',
        target_size=(640, 640),
        instance_key='gt_kernels'),
    dict(type='Pad', size_divisor=32),
    dict(
        type='CustomFormatBundle',
        keys=['gt_kernels', 'gt_mask'],
        visualize=dict(flag=False, boundary_key='gt_kernels')),
    dict(type='Collect', keys=['img', 'gt_kernels', 'gt_mask'])
]
test_pipeline = [
    dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1200, 800),
        flip=False,
        transforms=[
            dict(type='Resize', img_scale=(1200, 800), keep_ratio=True),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=2,
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='IcdarDataset',
        ann_file='data/icdar2015/annotations/train.json',
        img_prefix='data/icdar2015/train',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(
                type='LoadTextAnnotations',
                with_bbox=True,
                with_mask=True,
                poly2mask=False),
            dict(
                type='ColorJitter',
                brightness=0.12549019607843137,
                saturation=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(
                type='ScaleAspectJitter',
                img_scale=[(1200, 800)],
                ratio_range=(0.5, 3),
                aspect_ratio_range=(1, 1),
                multiscale_mode='value',
                long_size_bound=1280,
                short_size_bound=640,
                resize_type='long_short_bound',
                keep_ratio=False),
            dict(type='PSENetTargets'),
            dict(type='RandomFlip', flip_ratio=0.5, direction='horizontal'),
            dict(type='RandomRotateTextDet'),
            dict(
                type='RandomCropInstances',
                target_size=(640, 640),
                instance_key='gt_kernels'),
            dict(type='Pad', size_divisor=32),
            dict(
                type='CustomFormatBundle',
                keys=['gt_kernels', 'gt_mask'],
                visualize=dict(flag=False, boundary_key='gt_kernels')),
            dict(type='Collect', keys=['img', 'gt_kernels', 'gt_mask'])
        ]),
    val=dict(
        type='IcdarDataset',
        ann_file='data/icdar2015/annotations/val.json',
        img_prefix='data/icdar2015/val',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1200, 800),
                flip=False,
                transforms=[
                    dict(
                        type='Resize', img_scale=(1200, 800), keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='IcdarDataset',
        ann_file='data/icdar2015/annotations/val.json',
        img_prefix='data/icdar2015/val',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1200, 800),
                flip=False,
                transforms=[
                    dict(
                        type='Resize', img_scale=(1200, 800), keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=10, metric='hmean-iou')
work_dir = 'workdir1'
gpu_ids = range(0, 1)
```

Here's the error log
```2021-12-14 16:27:51,892 - mmocr - INFO - workflow: [('train', 1)], max: 600 epochs
2021-12-14 16:27:51,892 - mmocr - INFO - Checkpoints will be saved to /home/yangmoyi/mmocr/workdir1 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 217, in <module>
    main()
  File "tools/train.py", line 213, in main
    meta=meta)
  File "/home/yangmoyi/mmocr/mmocr/apis/train.py", line 154, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 195, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 218, in prepare_train_img
    return self.pipeline(results)
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/mmdet/datasets/pipelines/loading.py", line 377, in __call__
    results = self._load_masks(results)
  File "/home/yangmoyi/mmocr/mmocr/datasets/pipelines/loading.py", line 81, in _load_masks
    w)
  File "/home/yangmoyi/anaconda3/envs/mmocr030/lib/python3.7/site-packages/mmdet/core/mask/structures.py", line 592, in __init__
    assert isinstance(masks[0][0], np.ndarray)
IndexError: list index out of range
```

Here's an example of json label file.
[trainlabel.zip](https://github.com/open-mmlab/mmocr/files/7709952/trainlabel.zip)

There's might be some problems with the labels, but I generate them in the same way as how I did in mmdetection. My os is ubuntu20.04, name of class has already been changed in icdar dataset, everything seems ok.

Thanks again for this awesome project!

**Comment by Y-M-Y** [comment]
I solved  the problem temporarily, json labels in my dataset  'segmentation=[ ] '. However, PSENet need segmentation, so I generate a new json labels by using the converter voc2coco in mmdetetction. It works! Thank you for the space!
