### ISSUE TITLE
Module not found during `python setup.py install` on Windows

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmocr#689]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

Maybe we can add this package in requiements.

==

```
12:35:33  Installed c:\users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\numba-0.55.0rc1-py3.8-win-amd64.egg
12:35:33  Searching for lanms-neo==1.0.2
12:35:33  Reading https://pypi.org/simple/lanms-neo/
12:35:33  Downloading https://files.pythonhosted.org/packages/7b/fe/beff7e7e4455cb9f69c5734897ca8552a57f6423b062ec86b2ebc1d79c0d/lanms_neo-1.0.2.tar.gz#sha256=5ea9b19a9e9995f40d29a195b6e186df9aa337db5b46de5c1d0a7bdc04098586
12:35:33  Best match: lanms-neo 1.0.2
12:35:33  Processing lanms_neo-1.0.2.tar.gz
12:35:33  Writing C:\Users\user\AppData\Local\Temp\easy_install-9c_7pvgm\lanms_neo-1.0.2\setup.cfg
12:35:33  Running lanms_neo-1.0.2\setup.py -q bdist_egg --dist-dir C:\Users\user\AppData\Local\Temp\easy_install-9c_7pvgm\lanms_neo-1.0.2\egg-dist-tmp-i175x51y
12:35:34  Traceback (most recent call last):
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
12:35:34      yield saved
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
12:35:34      yield
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
12:35:34      _execfile(setup_script, ns)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
12:35:34      exec(code, globals, locals)
12:35:34    File "C:\Users\user\AppData\Local\Temp\easy_install-9c_7pvgm\lanms_neo-1.0.2\setup.py", line 5, in <module>
12:35:34      import warnings
12:35:34  ModuleNotFoundError: No module named 'pybind11'
12:35:34  
12:35:34  During handling of the above exception, another exception occurred:
12:35:34  
12:35:34  Traceback (most recent call last):
12:35:34    File "setup.py", line 170, in <module>
12:35:34      setup(
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\__init__.py", line 153, in setup
12:35:34      return distutils.core.setup(**attrs)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\distutils\core.py", line 148, in setup
12:35:34      dist.run_commands()
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\distutils\dist.py", line 966, in run_commands
12:35:34      self.run_command(cmd)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\distutils\dist.py", line 985, in run_command
12:35:34      cmd_obj.run()
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\install.py", line 67, in run
12:35:34      self.do_egg_install()
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
12:35:34      cmd.run(show_deprecation=False)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 408, in run
12:35:34      self.easy_install(spec, not self.no_deps)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 650, in easy_install
12:35:34      return self.install_item(None, spec, tmpdir, deps, True)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 697, in install_item
12:35:34      self.process_distribution(spec, dist, deps)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 744, in process_distribution
12:35:34      distros = WorkingSet([]).resolve(
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
12:35:34      dist = best[req.key] = env.best_match(
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
12:35:34      return self.obtain(req, installer)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
12:35:34      return installer(requirement)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 669, in easy_install
12:35:34      return self.install_item(spec, dist.location, tmpdir, deps)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
12:35:34      dists = self.install_eggs(spec, download, tmpdir)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
12:35:34      return self.build_and_install(setup_script, setup_base)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 1162, in build_and_install
12:35:34      self.run_setup(setup_script, setup_base, args)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
12:35:34      run_setup(setup_script, args)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 262, in run_setup
12:35:34      raise
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\contextlib.py", line 131, in __exit__
12:35:34      self.gen.throw(type, value, traceback)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
12:35:34      yield
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\contextlib.py", line 131, in __exit__
12:35:34      self.gen.throw(type, value, traceback)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
12:35:34      saved_exc.resume()
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 143, in resume
12:35:34      raise exc.with_traceback(self._tb)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
12:35:34      yield saved
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
12:35:34      yield
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
12:35:34      _execfile(setup_script, ns)
12:35:34    File "C:\Users\user\miniconda3\envs\mmocrv0.4.0_mmdetv2.19.1_mmcvv1.4.1_cuda113_py38_torch1.10.0\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
12:35:34      exec(code, globals, locals)
12:35:34    File "C:\Users\user\AppData\Local\Temp\easy_install-9c_7pvgm\lanms_neo-1.0.2\setup.py", line 5, in <module>
12:35:34      import warnings
12:35:34  ModuleNotFoundError: No module named 'pybind11'
12:35:34  Python setup.py install failed.
```
**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmocr/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

```none
A placeholder for traceback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by er2q** [comment]
pip install pybind11 -i https://pypi.tuna.tsinghua.edu.cn/simple
