### ISSUE TITLE
fine tune, train for other lang

### ISSUE THREAD

**Issue by Globolik** [open-mmlab/mmocr#741]
Hi mmocr team!
Great job on this project. I have two questions:
1)  What steps i need to do to train recognition model for my native language. (SAR or ABINet models)?
2) How to fine tune TextSnake pretrained model?

In the end i want to OCR this type of images
![thresh_850](https://user-images.githubusercontent.com/86630669/150100286-71dd4b98-8b57-499c-81aa-b1e69d417a09.png)

**Comment by cuhk-hbsun** [comment]
1.1 Prepare your own data like `imgs` and `label.txt` under [ocr_toy_dataset](https://github.com/open-mmlab/mmocr/tree/main/tests/data/ocr_toy_dataset). 
1.2 Modify [line](https://github.com/open-mmlab/mmocr/blob/main/configs/_base_/recog_models/sar.py#L2) to `type='AttnConvertor', dict_list=[x, x, x, x], with_unknown=True)`. ([x, x, x, x] is the characters of your language)
1.3 Train `SAR` with config file [sar_r31_parallel_decoder_toy_dataset.py](https://github.com/open-mmlab/mmocr/blob/main/configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py)

2.1 Add line `load_from = "released_checkpoint.pth"` in the config file.
2.2 Prepare your own text detect dataset.

**Comment by Globolik** [comment]
Much thanks @cuhk-hbsun, can't wait to try this out!

**Comment by Globolik** [comment]
I have one more question if you don't mind @cuhk-hbsun.
> 1.1 Prepare your own data like `imgs`

I've got this image with 2 words. If TextSnake detects each word and then SAR model recognise them one by one,
![image](https://user-images.githubusercontent.com/86630669/150294178-7eeff121-e4e0-4952-8ed3-f0eaf23b5d68.png)
Then for the training in 1.1 `imgs` i need only images that contain 1 word?
![image](https://user-images.githubusercontent.com/86630669/150294365-e8979b9b-449a-4ecc-86cd-a73a3b9c515a.png)

**Comment by cuhk-hbsun** [comment]
> I have one more question if you don't mind @cuhk-hbsun.
> 
> > 1.1 Prepare your own data like `imgs`
> 
> I've got this image with 2 words. If TextSnake detects each word and then SAR model recognise them one by one, ![image](https://user-images.githubusercontent.com/86630669/150294178-7eeff121-e4e0-4952-8ed3-f0eaf23b5d68.png) Then for the training in 1.1 `imgs` i need only images that contain 1 word? ![image](https://user-images.githubusercontent.com/86630669/150294365-e8979b9b-449a-4ecc-86cd-a73a3b9c515a.png)

It is not necessary to make sure that each image contains only one word. Both one word or two words in one image are OK.

**Comment by Globolik** [comment]
hi, i'm training SAR model like u sad @cuhk-hbsun and get error:
```Traceback (most recent call last):
  File "tools/train.py", line 224, in <module>
    main()
  File "tools/train.py", line 101, in main
    cfg = Config.fromfile(args.config)
  File "/home/globolik/anaconda3/envs/mmocr_2/lib/python3.7/site-packages/mmcv/utils/config.py", line 335, in fromfile
    use_predefined_variables)
  File "/home/globolik/anaconda3/envs/mmocr_2/lib/python3.7/site-packages/mmcv/utils/config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/globolik/anaconda3/envs/mmocr_2/lib/python3.7/site-packages/mmcv/utils/config.py", line 206, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/globolik/anaconda3/envs/mmocr_2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpbg6w7unf/tmptvhqv13z.py", line 2, in <module>
NameError: name 'а' is not defined
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f390aaf7320>
Traceback (most recent call last):
  File "/home/globolik/anaconda3/envs/mmocr_2/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/globolik/anaconda3/envs/mmocr_2/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbg6w7unf/tmptvhqv13z.py'```

**Comment by Globolik** [comment]
solved by putting an actual strings instead of vars `dict_list=['а', 'б', 'в', 'г', ....
