### ISSUE TITLE
evaluation of trained model

### ISSUE THREAD

**Issue by Globolik** [open-mmlab/mmocr#783]
I'm trying to get label from SAR model i just trained on my data. I took code from colab tutorial
```
from mmocr.apis import model_inference
from  mmocr.apis import init_detector
from mmcv import Config
from mmocr.apis import disable_text_recog_aug_test
img = './tests/data/ocr_toy_dataset/imgs/00001.png'
checkpoint = "/home/globolik/mmocr/work_dirs/sar_r31_parallel_decoder_toy_dataset/epoch_5.pth"
# out_file = 'outputs/1036169.jpg'
cfg = Config.fromfile('./configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py', )
model = init_detector(cfg, checkpoint)
# if model.cfg.data.test['type'] == 'ConcatDataset':
# model.cfg.data.test.pipeline = model.cfg.data.test['datasets'][0].pipeline
result = model_inference(model, img)
print(f'result: {result}')
```
And i stuck on the error
```
/home/globolik/anaconda3/envs/mmocr_2/bin/python /home/globolik/mmocr/12.py 
load checkpoint from local path: /home/globolik/mmocr/work_dirs/sar_r31_parallel_decoder_toy_dataset/epoch_5.pth
Traceback (most recent call last):
  File "/home/globolik/mmocr/12.py", line 38, in <module>
    result = model_inference(model, img,)
  File "/home/globolik/mmocr/mmocr/apis/inference.py", line 113, in model_inference
    test_pipeline = Compose(cfg.data.test.pipeline)
  File "/home/globolik/anaconda3/envs/mmocr_2/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/globolik/anaconda3/envs/mmocr_2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'MultiRotateAugOCR is not in the pipeline registry'
```
What i should do to get labels from my saved trained checkpoint?

**Comment by Globolik** [comment]
i solved problem by reading [#738](https://github.com/open-mmlab/mmocr/issues/738)]
with code 
import mmcv
from mmocr.utils.ocr import MMOCR
```
img_path = img
# det_config = 'xxx'
# det_ckpt = 'xxx'
recog_config = cfg
recog_ckpt = checkpoint
ocr = MMOCR(det=None, recog_config=recog_config, recog_ckpt=recog_ckpt)
results = ocr.readtext(img_path, details=True, print_result=True)
```
But, my result is only one word, in the labels there two words.
What should i change to train/test model to output two words?

**Comment by gaotongxiao** [comment]
Yes. You can also refer to https://github.com/open-mmlab/mmocr/issues/725 for a detailed guide

**Comment by Globolik** [comment]
tnx @gaotongxiao
