### ISSUE TITLE
KeyError: 'meta'

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#83]
getting `KeyError: 'meta'` when rying to predict using a psenet model
```
(open-mmlab) home@home-lnx:~/programs/mmocr$ python demo/image_demo.py demo/1.jpg configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py ./psenet_r50_fpnf_600e_icdar2015_pretrain-eefd8fe6.pth demo/output.jpg
Traceback (most recent call last):
  File "demo/image_demo.py", line 44, in <module>
    main()
  File "demo/image_demo.py", line 26, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 43, in init_detector
    if 'CLASSES' in checkpoint['meta']:
KeyError: 'meta'
```

**Comment by cuhk-hbsun** [comment]
Please use the following commands to update(resave) the ckpt first, and we will update the checkpoint as soon as possible.
```bash
import torch

in_file = 'psenet_r50_fpnf_600e_icdar2015_pretrain-eefd8fe6.pth'
checkpoint = torch.load(in_file, map_location='cpu')
checkpoint['meta'] = {'CLASSES': 0}
torch.save(checkpoint, in_file)
```

**Comment by seekingdeep** [comment]
@cuhk-hbsun Thanks, this solved it
