### ISSUE TITLE
Training Not Started

### ISSUE THREAD

**Issue by payal211** [open-mmlab/mmocr#840]
HI @gaotongxiao 

I raised the query #816 and as per your suggestion when I run this command it gives me below error and training is not started.

Command I run :  ./tools/dist_train.sh configs/textrecog/sar/sar_r31_parallel_decoder_custom_dataset.py sar 4

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 17, in <module>
    from mmocr.apis import init_random_seed, train_detector
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmocr/apis/__init__.py", line 2, in <module>
    from .inference import init_detector, model_inference
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmocr/apis/inference.py", line 10, in <module>
    from mmdet.core import get_classes
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/__init__.py", line 6, in <module>
    from .hook import *  # noqa: F401, F403
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/hook/__init__.py", line 5, in <module>
    from .sync_norm_hook import SyncNormHook
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/hook/sync_norm_hook.py", line 8, in <module>
    from ..utils.dist_utils import all_reduce_dict
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/__init__.py", line 4, in <module>
    from .misc import (center_of_mass, filter_scores_and_topk, flip_tensor,
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 8, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/__init__.py", line 3, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/structures.py", line 7, in <module>
    import pycocotools.mask as maskUtils
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "./tools/train.py", line 17, in <module>
    from mmocr.apis import init_random_seed, train_detector
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmocr/apis/__init__.py", line 2, in <module>
    from .inference import init_detector, model_inference
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmocr/apis/inference.py", line 10, in <module>
    from mmdet.core import get_classes
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/__init__.py", line 6, in <module>
    from .hook import *  # noqa: F401, F403
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/hook/__init__.py", line 5, in <module>
    from .sync_norm_hook import SyncNormHook
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/hook/sync_norm_hook.py", line 8, in <module>
    from ..utils.dist_utils import all_reduce_dict
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/__init__.py", line 4, in <module>
    from .misc import (center_of_mass, filter_scores_and_topk, flip_tensor,
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 8, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/__init__.py", line 3, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/structures.py", line 7, in <module>
    import pycocotools.mask as maskUtils
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "./tools/train.py", line 17, in <module>
    from mmocr.apis import init_random_seed, train_detector
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmocr/apis/__init__.py", line 2, in <module>
    from .inference import init_detector, model_inference
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmocr/apis/inference.py", line 10, in <module>
    from mmdet.core import get_classes
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/__init__.py", line 6, in <module>
    from .hook import *  # noqa: F401, F403
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/hook/__init__.py", line 5, in <module>
    from .sync_norm_hook import SyncNormHook
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/hook/sync_norm_hook.py", line 8, in <module>
    from ..utils.dist_utils import all_reduce_dict
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/__init__.py", line 4, in <module>
    from .misc import (center_of_mass, filter_scores_and_topk, flip_tensor,
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 8, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/__init__.py", line 3, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/structures.py", line 7, in <module>
    import pycocotools.mask as maskUtils
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "./tools/train.py", line 17, in <module>
    from mmocr.apis import init_random_seed, train_detector
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmocr/apis/__init__.py", line 2, in <module>
    from .inference import init_detector, model_inference
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmocr/apis/inference.py", line 10, in <module>
    from mmdet.core import get_classes
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/__init__.py", line 6, in <module>
    from .hook import *  # noqa: F401, F403
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/hook/__init__.py", line 5, in <module>
    from .sync_norm_hook import SyncNormHook
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/hook/sync_norm_hook.py", line 8, in <module>
    from ..utils.dist_utils import all_reduce_dict
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/__init__.py", line 4, in <module>
    from .misc import (center_of_mass, filter_scores_and_topk, flip_tensor,
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 8, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/__init__.py", line 3, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/mask/structures.py", line 7, in <module>
    import pycocotools.mask as maskUtils
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/.conda/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/textrecog/sar/sar_r31_parallel_decoder_ceat_dataset.py', '--work-dir=sar', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

Can you please help me to resolve this?

Thanks.

**Comment by gaotongxiao** [comment]
You just need to upgrade your numpy: https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp
