### ISSUE TITLE
The evaluation of the text detector takes long (hours!!!)

### ISSUE THREAD

**Issue by EMRAN-SALEH-CORSEARCH** [open-mmlab/mmocr#847]
I try to train and finetune the  pretrained PSENet text decetion using textOCR dataset. 
The training dataset has: 21791 images
The validation dataset has: 3328 images

I made the validation after each training epoch
I run the system on instance with 16GB memory GPU

Two issuse I have faced here: 

**1- The evaluation takes longs hours (Why?!!!! why it needs hours to evaluate a model on only 3328 images?) and why it is repeated many times. I ended up to an error as well. I provide the log and the and the configuration files details below.**  

**2022-03-15 20:51:06,645 - mmocr - INFO - Evaluating hmean-iou...
2022-03-15 21:50:13,818 - mmocr - INFO - thr 0.30, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-15 22:49:17,456 - mmocr - INFO - thr 0.40, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-15 23:48:23,962 - mmocr - INFO - thr 0.50, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 00:47:34,881 - mmocr - INFO - thr 0.60, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 01:46:42,026 - mmocr - INFO - thr 0.70, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 02:45:41,413 - mmocr - INFO - thr 0.80, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 03:36:57,887 - mmocr - INFO - thr 0.90, recall: 0.610, precision: 0.845, hmean: 0.708**

**2- When I setup the workers_per_gpu >0 like 1 or 2  I shared memory error appears.**

**The configutation file details, I have just removed the datasets paths:**

checkpoint_config = dict(interval=1)
log_config = dict(interval=1, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = '/app/models/psenet_r50_fpnf_600e_icdar2015_pretrain-eefd8fe6.pth'
resume_from = None
workflow = [('train', 1), ('val', 1)]
optimizer = dict(type='Adam', lr=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[200, 400])
total_epochs = 200
model_poly = dict(
    type='PSENet',
    backbone=dict(
        type='mmdet.ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
        norm_eval=True,
        style='caffe'),
    neck=dict(
        type='FPNF',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        fusion_type='concat'),
    bbox_head=dict(
        type='PSEHead',
        text_repr_type='poly',
        in_channels=[256],
        out_channels=7,
        loss=dict(type='PSELoss')),
    train_cfg=None,
    test_cfg=None)
model_quad = dict(
    type='PSENet',
    backbone=dict(
        type='mmdet.ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
        norm_eval=True,
        style='caffe'),
    neck=dict(
        type='FPNF',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        fusion_type='concat'),
    bbox_head=dict(
        type='PSEHead',
        text_repr_type='quad',
        in_channels=[256],
        out_channels=7,
        loss=dict(type='PSELoss')),
    train_cfg=None,
    test_cfg=None)
dataset_type = 'IcdarDataset'
data_root = 'data/icdar2015'
train = dict(
    type='IcdarDataset',
    ann_file='ann PATH',
    img_prefix=img_prefix,
    pipeline=None)
test = dict(
    type='IcdarDataset',
    ann_file=ann PATH,
    img_prefix=img_prefix,
    pipeline=None)
train_list = [
    dict(
        type='IcdarDataset',
        ann_file=
        ann PATH,
        img_prefix=img_prefix,
        pipeline=None)
]
test_list = [
    dict(
        type='IcdarDataset',
        ann_file=ann PATH,
        img_prefix=img_prefix,
        pipeline=None)
]
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
    dict(
        type='LoadTextAnnotations',
        with_bbox=True,
        with_mask=True,
        poly2mask=False),
    dict(type='ColorJitter', brightness=0.12549019607843137, saturation=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(
        type='ScaleAspectJitter',
        img_scale=[(3000, 736)],
        ratio_range=(0.5, 3),
        aspect_ratio_range=(1, 1),
        multiscale_mode='value',
        long_size_bound=1280,
        short_size_bound=640,
        resize_type='long_short_bound',
        keep_ratio=False),
    dict(type='PSENetTargets'),
    dict(type='RandomFlip', flip_ratio=0.5, direction='horizontal'),
    dict(type='RandomRotateTextDet'),
    dict(
        type='RandomCropInstances',
        target_size=(640, 640),
        instance_key='gt_kernels'),
    dict(type='Pad', size_divisor=32),
    dict(
        type='CustomFormatBundle',
        keys=['gt_kernels', 'gt_mask'],
        visualize=dict(flag=False, boundary_key='gt_kernels')),
    dict(type='Collect', keys=['img', 'gt_kernels', 'gt_mask'])
]
img_scale_test_ctw1500 = (1280, 1280)
test_pipeline_ctw1500 = [
    dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1280, 1280),
        flip=False,
        transforms=[
            dict(type='Resize', img_scale=(1280, 1280), keep_ratio=True),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
img_scale_test_icdar2015 = (2240, 2240)
test_pipeline_icdar2015 = [
    dict(type='LoadImageFromFile', color_type='color_ignore_orientation'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2240, 2240),
        flip=False,
        transforms=[
            dict(type='Resize', img_scale=(1280, 1280), keep_ratio=True),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
model = dict(
    type='PSENet',
    backbone=dict(
        type='mmdet.ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),
        norm_eval=True,
        style='caffe'),
    neck=dict(
        type='FPNF',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        fusion_type='concat'),
    bbox_head=dict(
        type='PSEHead',
        text_repr_type='quad',
        in_channels=[256],
        out_channels=7,
        loss=dict(type='PSELoss')),
    train_cfg=None,
    test_cfg=None)
data = dict(
    samples_per_gpu=12,
    **workers_per_gpu=0,**
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1),
    train=dict(
        type='UniformConcatDataset',
        datasets=[
            dict(
                type='IcdarDataset',
                ann_file=
                ann PATH,
                img_prefix=img_prefix,
                pipeline=None)
        ],
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(
                type='LoadTextAnnotations',
                with_bbox=True,
                with_mask=True,
                poly2mask=False),
            dict(
                type='ColorJitter',
                brightness=0.12549019607843137,
                saturation=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(
                type='ScaleAspectJitter',
                img_scale=[(3000, 736)],
                ratio_range=(0.5, 3),
                aspect_ratio_range=(1, 1),
                multiscale_mode='value',
                long_size_bound=1280,
                short_size_bound=640,
                resize_type='long_short_bound',
                keep_ratio=False),
            dict(type='PSENetTargets'),
            dict(type='RandomFlip', flip_ratio=0.5, direction='horizontal'),
            dict(type='RandomRotateTextDet'),
            dict(
                type='RandomCropInstances',
                target_size=(640, 640),
                instance_key='gt_kernels'),
            dict(type='Pad', size_divisor=32),
            dict(
                type='CustomFormatBundle',
                keys=['gt_kernels', 'gt_mask'],
                visualize=dict(flag=False, boundary_key='gt_kernels')),
            dict(type='Collect', keys=['img', 'gt_kernels', 'gt_mask'])
        ]),
    val=dict(
        type='UniformConcatDataset',
        datasets=[
            dict(
                type='IcdarDataset',
                ann_file=
                ann PATH,
                img_prefix=img_prefix,
                pipeline=None)
        ],
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(2240, 2240),
                flip=False,
                transforms=[
                    dict(
                        type='Resize', img_scale=(1280, 1280),
                        keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='UniformConcatDataset',
        datasets=[
            dict(
                type='IcdarDataset',
                ann_file=
               ann PATH,
                img_prefix=img_prefix,
                pipeline=None)
        ],
        pipeline=[
            dict(
                type='LoadImageFromFile',
                color_type='color_ignore_orientation'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(2240, 2240),
                flip=False,
                transforms=[
                    dict(
                        type='Resize', img_scale=(1280, 1280),
                        keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))

evaluation = dict(interval=1, metric='hmean-iou', save_best='auto')
work_dir = '/app/models/PSE'
gpu_ids = range(0, 1)

=======================

**The log deatils:** 

 2.003, memory: 13381, loss_text: 0.1994, loss_kernel: 0.0469, loss: 0.2463
2022-03-15 19:32:24,394 - mmocr - INFO - Epoch [1][1319/1816]   lr: 1.000e-04, eta: 21 days, 22:13:35, time: 4.037, data_time: 1.974, memory: 13381, loss_text: 0.2058, loss_kernel: 0.0609, loss: 0.2667
2022-03-15 19:32:30,074 - mmocr - INFO - Epoch [1][1320/1816]   lr: 1.000e-04, eta: 21 days, 22:15:32, time: 5.680, data_time: 3.619, memory: 13381, loss_text: 0.1567, loss_kernel: 0.0662, loss: 0.2229
2022-03-15 19:32:34,880 - mmocr - INFO - Epoch [1][1321/1816]   lr: 1.000e-04, eta: 21 days, 22:13:29, time: 4.806, data_time: 2.733, memory: 13381, loss_text: 0.1839, loss_kernel: 0.0413, loss: 0.2252
2022-03-15 19:32:39,830 - mmocr - INFO - Epoch [1][1322/1816]   lr: 1.000e-04, eta: 21 days, 22:12:06, time: 4.950, data_time: 2.864, memory: 13381, loss_text: 0.2206, loss_kernel: 0.0667, loss: 0.2872

...

2022-03-15 20:15:24,773 - mmocr - INFO - Epoch [1][1814/1816]   lr: 1.000e-04, eta: 21 days, 20:54:11, time: 5.735, data_time: 3.685, memory: 13381, loss_text: 0.2128, loss_kernel: 0.0726, loss: 0.2855
2022-03-15 20:15:30,025 - mmocr - INFO - Epoch [1][1815/1816]   lr: 1.000e-04, eta: 21 days, 20:54:10, time: 5.252, data_time: 3.197, memory: 13381, loss_text: 0.1800, loss_kernel: 0.0476, loss: 0.2276
2022-03-15 20:15:35,306 - mmocr - INFO - Exp name: psenet_r50_fpnf_600e_textocr.py
2022-03-15 20:15:35,306 - mmocr - INFO - Epoch [1][1816/1816]   lr: 1.000e-04, eta: 21 days, 20:54:16, time: 5.281, data_time: 3.252, memory: 13381, loss_text: 0.3160, loss_kernel: 0.0704, loss: 0.3864
2022-03-15 20:15:35,307 - mmocr - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>] 3124/3124, 1.5 task/s, elapsed: 2130s, ETA:     0s2022-03-15 20:51:06,208 - mmocr - INFO -
Evaluateing /app/data/text_detection_dataset/textocr/instances_val.json with 3124 images now
**2022-03-15 20:51:06,645 - mmocr - INFO - Evaluating hmean-iou...
2022-03-15 21:50:13,818 - mmocr - INFO - thr 0.30, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-15 22:49:17,456 - mmocr - INFO - thr 0.40, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-15 23:48:23,962 - mmocr - INFO - thr 0.50, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 00:47:34,881 - mmocr - INFO - thr 0.60, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 01:46:42,026 - mmocr - INFO - thr 0.70, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 02:45:41,413 - mmocr - INFO - thr 0.80, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 03:36:57,887 - mmocr - INFO - thr 0.90, recall: 0.610, precision: 0.845, hmean: 0.708**
Traceback (most recent call last):
  File "tools/train.py", line 217, in <module>
    main()
  File "tools/train.py", line 213, in main
    meta=meta)
  File "/mmocr/mmocr/apis/train.py", line 154, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/opt/conda/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 19, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 381, in evaluate
    self._init_rule(self.rule, list(eval_res.keys())[0])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 194, in _init_rule
    raise ValueError(f'Cannot infer the rule for key '
ValueError: Cannot infer the rule for key 0_hmean-iou:recall, thus a specific rule must be specified.
[2] + Killed                     python tools/train.py configs/textdet/psenet/psenet_r50_fpnf_600e_textocr.py --work-dir /app/models/PSE --load-from /app/models/psenet_r50_fpnf_600e_icdar2015_pretrain-eefd8fe6.pth
#

**Comment by gaotongxiao** [comment]
The error is because the hook responsible for saving the best model cannot match the provided metric name with the actual  one, you can refer to this issue for a solution: https://github.com/open-mmlab/mmocr/issues/750

The bottleneck of the training and evaluation is the data loading process. `workers_per_gpus=0` makes everything happen on a single process and therefore data loading blocks consequential computing. Shared memory error usually occurs when you are trying to use multiple workers on docker but haven't gotten some options specified, ref: https://discuss.pytorch.org/t/shm-error-in-docker/22755

**Comment by EMRAN-SALEH-CORSEARCH** [comment]
Thank you! @gaotongxiao  I will check that. 
But why the evalution is long even if there is no error and looks repeated?  hours!. Look to the log?  and how to change that? 
2022-03-15 20:51:06,645 - mmocr - INFO - Evaluating hmean-iou...
2022-03-15 21:50:13,818 - mmocr - INFO - thr 0.30, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-15 22:49:17,456 - mmocr - INFO - thr 0.40, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-15 23:48:23,962 - mmocr - INFO - thr 0.50, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 00:47:34,881 - mmocr - INFO - thr 0.60, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 01:46:42,026 - mmocr - INFO - thr 0.70, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 02:45:41,413 - mmocr - INFO - thr 0.80, recall: 0.674, precision: 0.806, hmean: 0.734
2022-03-16 03:36:57,887 - mmocr - INFO - thr 0.90, recall: 0.610, precision: 0.845, hmean: 0.708

**Comment by EMRAN-SALEH-CORSEARCH** [comment]
I have checked the links you sent me and they are very helpful and fixed the errors.  
Thanks you!

The only remaining question the one I mentioned above about the evalaution takes very long for the  3328 images of validation dataset images, you can see the time stamp in the log above. I also see, the statistical measures recall, precision, hmean are calculated many times in the evaluation process (7 times), how can we control the number of calculating them?

**Comment by gaotongxiao** [comment]
Setting `workers_per_gpu=0` can block the follow-on evaluation when preparing data. You can set it as a positive integer to alleviate this issue.

Hmean is computed with different boundary score thresholds (`thr`), by which we hope to find the best configuration that minimizes the impact of "low-quality" boundaries on the final performance. The highest hmean among all the candidates will be reported as the final result, which is 0.734 in your example.

**Comment by gaotongxiao** [comment]
I'm closing this issue, but feel free to reopen it if you have any followup questions.
