### ISSUE TITLE
运行关键信息抽取网络sdmgr，测试脚本出错

### ISSUE THREAD

**Issue by NextGuido** [open-mmlab/mmocr#88]
您好，我在运行信息抽取网络的脚本时时，运行命令为`tools/kie_test_imgs.sh configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py checkpoints/sdmgr_unet16_60e_wildreceipt_20210405-16a47642.pth checkpoints/`，数据集和权重文件路径如下：

```
(ocr) zhoazj@zhoazj-ThinkPad-P15v-Gen-1:~/Desktop/codes/projects/github/mmocr$ tree data/ -L 2
data/
├── wildreceipt
│   ├── class_list.txt
│   ├── dict.txt
│   ├── image_files
│   ├── test.txt
│   └── train.txt
└── wildreceipt.tar

2 directories, 5 files
(ocr) zhoazj@zhoazj-ThinkPad-P15v-Gen-1:~/Desktop/codes/projects/github/mmocr$ tree checkpoints/
checkpoints/
├── _2021-04-18_22-01-30
├── crnn_academic-a723a1c5.pth
├── dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth
└── sdmgr_unet16_60e_wildreceipt_20210405-16a47642.pth

1 directory, 3 files

```

**然后，出现报错信息如下：**

```
Use load_from_local loader
[                                                  ] 0/472, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/kie_test_imgs.py", line 108, in <module>
    main()
  File "tools/kie_test_imgs.py", line 104, in main
    test(model, data_loader, args.show, args.show_dir)
  File "tools/kie_test_imgs.py", line 23, in test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 40, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/zhoazj/Desktop/codes/projects/github/mmocr/mmocr/models/kie/extractors/sdmgr.py", line 82, in forward_test
    x = self.extract_feat(img, gt_bboxes)
  File "/home/zhoazj/Desktop/codes/projects/github/mmocr/mmocr/models/kie/extractors/sdmgr.py", line 93, in extract_feat
    x = super().extract_feat(img)[-1]
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 54, in extract_feat
    x = self.backbone(img)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhoazj/Desktop/codes/projects/github/mmocr/mmocr/models/common/backbones/unet.py", line 480, in forward
    x = enc(x)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhoazj/Desktop/codes/projects/github/mmocr/mmocr/models/common/backbones/unet.py", line 181, in forward
    out = self.convs(x)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 198, in forward
    x = self.conv(x)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/home/zhoazj/anaconda3/envs/ocr/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 345, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 3, 3, 3], but got 5-dimensional input of size [1, 1, 3, 512, 512] instead
```

请问，是我的操作哪里出了问题吗？望解答，谢谢

**Comment by cuhk-hbsun** [comment]
你好，可以提供一下环境信息吗？运行`python mmocr/utils/collect_env.py`

**Comment by cuhk-hbsun** [comment]
主要是mmdet和mmcv的版本

**Comment by NextGuido** [comment]
@cuhk-hbsun 您好，环境信息如下（对了，使用的是CPU版本）：
```
(ocr) zhoazj@zhoazj-ThinkPad-P15v-Gen-1:~/Desktop/codes/projects/github/mmocr$ python mmocr/utils/collect_env.py
sys.platform: linux
Python: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
CUDA available: False
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0
OpenCV: 4.2.0
MMCV: 1.3.1
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: not available
MMOCR: 0.1.0+a68de22
```

**Comment by cuhk-hbsun** [comment]
ok, 我去check一下cpu版本能否正常运行

**Comment by NextGuido** [comment]
> ok, 我去check一下cpu版本能否正常运行

hello，请问这边有进一步消息吗？

**Comment by ndcuong91** [comment]
I still encounterd the same error yesterday. Is there any update for that?
