### ISSUE TITLE
numpy.ndarray size changed in latest master

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#91]
when running detection using the latest master branch, which is installed on a new environment using the latest i[nstall.md](https://github.com/open-mmlab/mmocr/blob/main/docs/install.md):
```
(mmdet) home@home-lnx:~/programs/mmocr$ python demo/image_demo.py demo/demo_text_det.jpg ./configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py ./dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth demo/demo_text_det_pred.jpg
Traceback (most recent call last):
  File "demo/image_demo.py", line 5, in <module>
    from mmdet.apis import init_detector
  File "/home/home/programs/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/home/programs/mmdetection/mmdet/apis/inference.py", line 10, in <module>
    from mmdet.core import get_classes
  File "/home/home/programs/mmdetection/mmdet/core/__init__.py", line 5, in <module>
    from .mask import *  # noqa: F401, F403
  File "/home/home/programs/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/home/programs/mmdetection/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
  File "/home/home/anaconda3/envs/mmdet/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by seekingdeep** [comment]
i think issues #91 and #92 are caused by conflicts in the installed requirements.
note that i used the official [install.md](https://github.com/open-mmlab/mmocr/blob/main/docs/install.md) to install the requirements.

Thus it would be better to include an `environment.yml`, which can be created using:
```
conda env export > environment.yml
```

**Comment by seekingdeep** [comment]
this issue seems to be caused by  #74 and some conflicts in the requirements versions

**Comment by cuhk-hbsun** [comment]
Pls pull the latest code, and check whether the bug exists or not.

**Comment by seekingdeep** [comment]
The latest commits have solved this issue, good job.
