### ISSUE TITLE
SATRN export onnx error

### ISSUE THREAD

**Issue by songyanbei** [open-mmlab/mmocr#912]
您好，我把SATRN-small的banckbone换成了VGG，同时增加了类别数，模型的训练和评测都是正常的，但是在导出onnx的时候报错了，请问这个该怎么解决呢？
```
python3 tools/deployment/pytorch2onnx.py ./configs/textrecog/satrn/satrn_small.py ./work_dirs/satrn_medical_small_40/epoch_15.pth recog /opt/worker/mmocr/data/medical/train/BJSH0124medicinetrain/02553c85d16e4e86bc684e2
c82211392_20.jpg --opset-version 14
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 355, in <module>
    main()
  File "tools/deployment/pytorch2onnx.py", line 351, in main
    dynamic_export=args.dynamic_export)
  File "tools/deployment/pytorch2onnx.py", line 202, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 729, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 545, in _model_to_graph
    _export_onnx_opset_version)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by gaotongxiao** [comment]
Hi, for deployment-related issues, please reraise them to [MMDeploy](https://github.com/open-mmlab/mmdeploy/issues). BTW, SATRN is not officially supported by MMDeploy yet, so it might take a longer time for them to respond.
