### ISSUE TITLE
TypeError: list indices must be integers or slices, not torch.device

### ISSUE THREAD

**Issue by seekingdeep** [open-mmlab/mmocr#92]
when trying to predict:
```
(open-mmlab) home@home-lnx:~/programs/mmocr$ python demo/image_demo.py demo/1.jpg configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py ./dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth demo/output.jpg
/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
Traceback (most recent call last):
  File "demo/image_demo.py", line 44, in <module>
    main()
  File "demo/image_demo.py", line 32, in main
    result = model_inference(model, args.img)
  File "/home/home/programs/mmocr/mmocr/apis/inference.py", line 53, in model_inference
    data = scatter(data, [device])[0]
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 44, in scatter
    return scatter_map(inputs)
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 34, in scatter_map
    out = list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 29, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 31, in scatter_map
    out = list(map(list, zip(*map(scatter_map, obj))))
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 27, in scatter_map
    return Scatter.forward(target_gpus, obj.data)
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/_functions.py", line 72, in forward
    streams = [_get_stream(device) for device in target_gpus]
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/_functions.py", line 72, in <listcomp>
    streams = [_get_stream(device) for device in target_gpus]
  File "/home/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 115, in _get_stream
    if _streams[device] is None:
TypeError: list indices must be integers or slices, not torch.device
```

**Comment by seekingdeep** [comment]
i think issues #91 and #92 are caused by conflicts in the installed requirements.
note that i used the official [install.md](https://github.com/open-mmlab/mmocr/blob/main/docs/install.md) to install the requirements.

Thus it would be better to include an `environment.yml`, which can be created using:
```
conda env export > environment.yml
```

**Comment by seekingdeep** [comment]
found something, it was caused after https://github.com/open-mmlab/mmocr/pull/74

**Comment by cuhk-hbsun** [comment]
The bug has been fixed in https://github.com/open-mmlab/mmocr/pull/87. Please wait for merge.

**Comment by cuhk-hbsun** [comment]
Fixed, please pull the latest code.

**Comment by jeffreykuang** [comment]
@seekingdeep, please help to validate if your bug is fixed or not with the latest code. If yes, we will close this issue

**Comment by seekingdeep** [comment]
The latest commits have solved this issue, good job.
