### ISSUE TITLE
work question

### ISSUE THREAD

**Issue by Zhaohaojie4598** [open-mmlab/mmocr#940]
Hello.When I run this code as follow, python E:/mmocr-main/tools/data/textdet/totaltext_converter.py E:/totaltext -o E:/totaltext --split-list training test ,I get some wrong warnings like
Traceback (most recent call last):
  File "E:/mmocr-main/tools/data/textdet/totaltext_converter.py", line 407, in <module>
    main()
  File "E:/mmocr-main/tools/data/textdet/totaltext_converter.py", line 402, in main
    image_infos = collect_annotations(files, nproc=args.nproc)
  File "E:/mmocr-main/tools/data/textdet/totaltext_converter.py", line 69, in collect_annotations
    images = mmcv.track_progress(load_img_info, files)
  File "D:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\progressbar.py", line 92, in track_progress
    results.append(func(task, **kwargs))
  File "E:/mmocr-main/tools/data/textdet/totaltext_converter.py", line 357, in load_img_info
    img_info = load_mat_info(img_info, gt_file)
  File "E:/mmocr-main/tools/data/textdet/totaltext_converter.py", line 133, in load_mat_info
    contours, texts = get_contours_mat(gt_file)
  File "E:/mmocr-main/tools/data/textdet/totaltext_converter.py", line 91, in get_contours_mat
    data_polygt = data.get('polygt', data['gt'])
KeyError: 'gt'
what should I do.

**Comment by xinke-wang** [comment]
Hi, this is because the `latest` and `legacy` annotation files of the total text use a different dict key. In the legacy one it uses `polygt` while in the latest one it uses `gt`.

In this case, it seems that you are using the legacy annotation, so you have to modify the [Line91](https://github.com/open-mmlab/mmocr/blob/main/tools/data/textdet/totaltext_converter.py#L91) in `textdet/totaltext_converter.py` as follows:

```python
# data_polygt = data.get('polygt', data['gt'])`
data_polygt = data.get('polygt', data['polygt'])`

```

**Comment by gaotongxiao** [comment]
@xinke-wang Yes please!

**Comment by Zhaohaojie4598** [comment]
> Hi, this is because the `latest` and `legacy` annotation files of the total text use a different dict key. In the legacy one it uses `polygt` while in the latest one it uses `gt`.
> 
> In this case, it seems that you are using the legacy annotation, so you have to modify the [Line91](https://github.com/open-mmlab/mmocr/blob/main/tools/data/textdet/totaltext_converter.py#L91) in `textdet/totaltext_converter.py` as follows:
> 
> ```python
> # data_polygt = data.get('polygt', data['gt'])
> data_polygt = data.get('polygt', data['polygt'])
> ```
> 
> @gaotongxiao Shall we add a version checker to the totaltext data converter, so the users don't have to modify the key themselves.

thank you very much
